# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'plotguiretina.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_PythIon(object):
    def setupUi(self, PythIon):
        PythIon.setObjectName(_fromUtf8("PythIon"))
        PythIon.resize(1952, 1321)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(PythIon.sizePolicy().hasHeightForWidth())
        PythIon.setSizePolicy(sizePolicy)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8("../Downloads/PythIon/pythionlogo.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        PythIon.setWindowIcon(icon)
        PythIon.setAutoFillBackground(False)
        PythIon.setDockNestingEnabled(True)
        self.centralwidget = QtGui.QWidget(PythIon)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.centralwidget.sizePolicy().hasHeightForWidth())
        self.centralwidget.setSizePolicy(sizePolicy)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.gridLayout_10 = QtGui.QGridLayout(self.centralwidget)
        self.gridLayout_10.setObjectName(_fromUtf8("gridLayout_10"))
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setSizeConstraint(QtGui.QLayout.SetMaximumSize)
        self.horizontalLayout_4.setSpacing(10)
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.groupBox = QtGui.QGroupBox(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox.sizePolicy().hasHeightForWidth())
        self.groupBox.setSizePolicy(sizePolicy)
        self.groupBox.setMinimumSize(QtCore.QSize(350, 250))
        self.groupBox.setMaximumSize(QtCore.QSize(350, 250))
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.gridLayout_2 = QtGui.QGridLayout(self.groupBox)
        self.gridLayout_2.setSizeConstraint(QtGui.QLayout.SetDefaultConstraint)
        self.gridLayout_2.setContentsMargins(20, 10, 20, 10)
        self.gridLayout_2.setSpacing(20)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.previousfilebutton = QtGui.QPushButton(self.groupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.previousfilebutton.sizePolicy().hasHeightForWidth())
        self.previousfilebutton.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.previousfilebutton.setFont(font)
        self.previousfilebutton.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.previousfilebutton.setAutoFillBackground(False)
        self.previousfilebutton.setObjectName(_fromUtf8("previousfilebutton"))
        self.gridLayout_2.addWidget(self.previousfilebutton, 2, 0, 1, 1)
        self.loaddatabutton = QtGui.QPushButton(self.groupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.loaddatabutton.sizePolicy().hasHeightForWidth())
        self.loaddatabutton.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.loaddatabutton.setFont(font)
        self.loaddatabutton.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.loaddatabutton.setAutoFillBackground(False)
        self.loaddatabutton.setObjectName(_fromUtf8("loaddatabutton"))
        self.gridLayout_2.addWidget(self.loaddatabutton, 4, 1, 1, 1)
        self.cutbutton = QtGui.QPushButton(self.groupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cutbutton.sizePolicy().hasHeightForWidth())
        self.cutbutton.setSizePolicy(sizePolicy)
        self.cutbutton.setMinimumSize(QtCore.QSize(0, 5))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.cutbutton.setFont(font)
        self.cutbutton.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.cutbutton.setAutoFillBackground(False)
        self.cutbutton.setObjectName(_fromUtf8("cutbutton"))
        self.gridLayout_2.addWidget(self.cutbutton, 0, 1, 1, 1)
        self.nextfilebutton = QtGui.QPushButton(self.groupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.nextfilebutton.sizePolicy().hasHeightForWidth())
        self.nextfilebutton.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.nextfilebutton.setFont(font)
        self.nextfilebutton.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.nextfilebutton.setAutoFillBackground(False)
        self.nextfilebutton.setObjectName(_fromUtf8("nextfilebutton"))
        self.gridLayout_2.addWidget(self.nextfilebutton, 1, 0, 1, 1)
        self.loadbutton = QtGui.QPushButton(self.groupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.loadbutton.sizePolicy().hasHeightForWidth())
        self.loadbutton.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.loadbutton.setFont(font)
        self.loadbutton.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.loadbutton.setAutoFillBackground(False)
        self.loadbutton.setObjectName(_fromUtf8("loadbutton"))
        self.gridLayout_2.addWidget(self.loadbutton, 0, 0, 1, 1)
        self.clearscatterbutton = QtGui.QPushButton(self.groupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.clearscatterbutton.sizePolicy().hasHeightForWidth())
        self.clearscatterbutton.setSizePolicy(sizePolicy)
        self.clearscatterbutton.setMinimumSize(QtCore.QSize(0, 5))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.clearscatterbutton.setFont(font)
        self.clearscatterbutton.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.clearscatterbutton.setAutoFillBackground(False)
        self.clearscatterbutton.setObjectName(_fromUtf8("clearscatterbutton"))
        self.gridLayout_2.addWidget(self.clearscatterbutton, 4, 0, 1, 1)
        self.invertbutton = QtGui.QPushButton(self.groupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.invertbutton.sizePolicy().hasHeightForWidth())
        self.invertbutton.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.invertbutton.setFont(font)
        self.invertbutton.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.invertbutton.setAutoFillBackground(False)
        self.invertbutton.setObjectName(_fromUtf8("invertbutton"))
        self.gridLayout_2.addWidget(self.invertbutton, 3, 0, 1, 1)
        self.analyzebutton = QtGui.QPushButton(self.groupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.analyzebutton.sizePolicy().hasHeightForWidth())
        self.analyzebutton.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.analyzebutton.setFont(font)
        self.analyzebutton.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.analyzebutton.setAutoFillBackground(False)
        self.analyzebutton.setObjectName(_fromUtf8("analyzebutton"))
        self.gridLayout_2.addWidget(self.analyzebutton, 2, 1, 1, 1)
        self.baselinebutton = QtGui.QPushButton(self.groupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.baselinebutton.sizePolicy().hasHeightForWidth())
        self.baselinebutton.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.baselinebutton.setFont(font)
        self.baselinebutton.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.baselinebutton.setAutoFillBackground(False)
        self.baselinebutton.setObjectName(_fromUtf8("baselinebutton"))
        self.gridLayout_2.addWidget(self.baselinebutton, 1, 1, 1, 1)
        self.fitbutton = QtGui.QPushButton(self.groupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.fitbutton.sizePolicy().hasHeightForWidth())
        self.fitbutton.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.fitbutton.setFont(font)
        self.fitbutton.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.fitbutton.setAutoFillBackground(False)
        self.fitbutton.setObjectName(_fromUtf8("fitbutton"))
        self.gridLayout_2.addWidget(self.fitbutton, 3, 1, 1, 1)
        self.horizontalLayout_4.addWidget(self.groupBox)
        self.groupBox1 = QtGui.QGroupBox(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox1.sizePolicy().hasHeightForWidth())
        self.groupBox1.setSizePolicy(sizePolicy)
        self.groupBox1.setMinimumSize(QtCore.QSize(450, 250))
        self.groupBox1.setMaximumSize(QtCore.QSize(450, 250))
        self.groupBox1.setObjectName(_fromUtf8("groupBox1"))
        self.horizontalLayout = QtGui.QHBoxLayout(self.groupBox1)
        self.horizontalLayout.setSizeConstraint(QtGui.QLayout.SetNoConstraint)
        self.horizontalLayout.setMargin(5)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.verticalLayout_5 = QtGui.QVBoxLayout()
        self.verticalLayout_5.setObjectName(_fromUtf8("verticalLayout_5"))
        self.label = QtGui.QLabel(self.groupBox1)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setMinimumSize(QtCore.QSize(250, 0))
        self.label.setMaximumSize(QtCore.QSize(250, 16777215))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.label.setFont(font)
        self.label.setObjectName(_fromUtf8("label"))
        self.verticalLayout_5.addWidget(self.label)
        self.label_2 = QtGui.QLabel(self.groupBox1)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_2.sizePolicy().hasHeightForWidth())
        self.label_2.setSizePolicy(sizePolicy)
        self.label_2.setMinimumSize(QtCore.QSize(250, 0))
        self.label_2.setMaximumSize(QtCore.QSize(250, 16777215))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.label_2.setFont(font)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.verticalLayout_5.addWidget(self.label_2)
        self.label_5 = QtGui.QLabel(self.groupBox1)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_5.sizePolicy().hasHeightForWidth())
        self.label_5.setSizePolicy(sizePolicy)
        self.label_5.setMinimumSize(QtCore.QSize(250, 0))
        self.label_5.setMaximumSize(QtCore.QSize(250, 16777215))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.label_5.setFont(font)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.verticalLayout_5.addWidget(self.label_5)
        self.label_3 = QtGui.QLabel(self.groupBox1)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_3.sizePolicy().hasHeightForWidth())
        self.label_3.setSizePolicy(sizePolicy)
        self.label_3.setMinimumSize(QtCore.QSize(250, 0))
        self.label_3.setMaximumSize(QtCore.QSize(250, 16777215))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.label_3.setFont(font)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.verticalLayout_5.addWidget(self.label_3)
        self.label_6 = QtGui.QLabel(self.groupBox1)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_6.sizePolicy().hasHeightForWidth())
        self.label_6.setSizePolicy(sizePolicy)
        self.label_6.setMinimumSize(QtCore.QSize(250, 0))
        self.label_6.setMaximumSize(QtCore.QSize(250, 16777215))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.label_6.setFont(font)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.verticalLayout_5.addWidget(self.label_6)
        self.horizontalLayout.addLayout(self.verticalLayout_5)
        self.verticalLayout_4 = QtGui.QVBoxLayout()
        self.verticalLayout_4.setSizeConstraint(QtGui.QLayout.SetDefaultConstraint)
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.LPentry = QtGui.QLineEdit(self.groupBox1)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.LPentry.sizePolicy().hasHeightForWidth())
        self.LPentry.setSizePolicy(sizePolicy)
        self.LPentry.setMinimumSize(QtCore.QSize(150, 0))
        self.LPentry.setMaximumSize(QtCore.QSize(150, 16777215))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.LPentry.setFont(font)
        self.LPentry.setAlignment(QtCore.Qt.AlignCenter)
        self.LPentry.setObjectName(_fromUtf8("LPentry"))
        self.verticalLayout_4.addWidget(self.LPentry)
        self.outputsamplerateentry = QtGui.QLineEdit(self.groupBox1)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.outputsamplerateentry.sizePolicy().hasHeightForWidth())
        self.outputsamplerateentry.setSizePolicy(sizePolicy)
        self.outputsamplerateentry.setMinimumSize(QtCore.QSize(150, 0))
        self.outputsamplerateentry.setMaximumSize(QtCore.QSize(150, 16777215))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.outputsamplerateentry.setFont(font)
        self.outputsamplerateentry.setAlignment(QtCore.Qt.AlignCenter)
        self.outputsamplerateentry.setObjectName(_fromUtf8("outputsamplerateentry"))
        self.verticalLayout_4.addWidget(self.outputsamplerateentry)
        self.eventbufferentry = QtGui.QLineEdit(self.groupBox1)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.eventbufferentry.sizePolicy().hasHeightForWidth())
        self.eventbufferentry.setSizePolicy(sizePolicy)
        self.eventbufferentry.setMinimumSize(QtCore.QSize(150, 0))
        self.eventbufferentry.setMaximumSize(QtCore.QSize(150, 16777215))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.eventbufferentry.setFont(font)
        self.eventbufferentry.setAlignment(QtCore.Qt.AlignCenter)
        self.eventbufferentry.setObjectName(_fromUtf8("eventbufferentry"))
        self.verticalLayout_4.addWidget(self.eventbufferentry)
        self.thresholdentry = QtGui.QLineEdit(self.groupBox1)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.thresholdentry.sizePolicy().hasHeightForWidth())
        self.thresholdentry.setSizePolicy(sizePolicy)
        self.thresholdentry.setMinimumSize(QtCore.QSize(150, 0))
        self.thresholdentry.setMaximumSize(QtCore.QSize(150, 16777215))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.thresholdentry.setFont(font)
        self.thresholdentry.setAlignment(QtCore.Qt.AlignCenter)
        self.thresholdentry.setObjectName(_fromUtf8("thresholdentry"))
        self.verticalLayout_4.addWidget(self.thresholdentry)
        self.levelthresholdentry = QtGui.QLineEdit(self.groupBox1)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.levelthresholdentry.sizePolicy().hasHeightForWidth())
        self.levelthresholdentry.setSizePolicy(sizePolicy)
        self.levelthresholdentry.setMinimumSize(QtCore.QSize(150, 0))
        self.levelthresholdentry.setMaximumSize(QtCore.QSize(150, 16777215))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.levelthresholdentry.setFont(font)
        self.levelthresholdentry.setAlignment(QtCore.Qt.AlignCenter)
        self.levelthresholdentry.setObjectName(_fromUtf8("levelthresholdentry"))
        self.verticalLayout_4.addWidget(self.levelthresholdentry)
        self.horizontalLayout.addLayout(self.verticalLayout_4)
        self.horizontalLayout_4.addWidget(self.groupBox1)
        self.gridLayout_10.addLayout(self.horizontalLayout_4, 0, 0, 1, 1)
        self.groupBox2 = QtGui.QGroupBox(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox2.sizePolicy().hasHeightForWidth())
        self.groupBox2.setSizePolicy(sizePolicy)
        self.groupBox2.setMinimumSize(QtCore.QSize(800, 275))
        self.groupBox2.setMaximumSize(QtCore.QSize(16777215, 275))
        self.groupBox2.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.groupBox2.setObjectName(_fromUtf8("groupBox2"))
        self.gridLayout_5 = QtGui.QGridLayout(self.groupBox2)
        self.gridLayout_5.setSizeConstraint(QtGui.QLayout.SetMinimumSize)
        self.gridLayout_5.setContentsMargins(10, 10, 10, 5)
        self.gridLayout_5.setVerticalSpacing(10)
        self.gridLayout_5.setObjectName(_fromUtf8("gridLayout_5"))
        self.meandelilabel = QtGui.QLabel(self.groupBox2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.meandelilabel.sizePolicy().hasHeightForWidth())
        self.meandelilabel.setSizePolicy(sizePolicy)
        self.meandelilabel.setMinimumSize(QtCore.QSize(1000, 25))
        self.meandelilabel.setMaximumSize(QtCore.QSize(3000, 30))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.meandelilabel.setFont(font)
        self.meandelilabel.setText(_fromUtf8(""))
        self.meandelilabel.setObjectName(_fromUtf8("meandelilabel"))
        self.gridLayout_5.addWidget(self.meandelilabel, 2, 0, 1, 1)
        self.meandwelllabel = QtGui.QLabel(self.groupBox2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.meandwelllabel.sizePolicy().hasHeightForWidth())
        self.meandwelllabel.setSizePolicy(sizePolicy)
        self.meandwelllabel.setMinimumSize(QtCore.QSize(100, 25))
        self.meandwelllabel.setMaximumSize(QtCore.QSize(3000, 25))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.meandwelllabel.setFont(font)
        self.meandwelllabel.setText(_fromUtf8(""))
        self.meandwelllabel.setObjectName(_fromUtf8("meandwelllabel"))
        self.gridLayout_5.addWidget(self.meandwelllabel, 3, 0, 1, 1)
        self.eventcounterlabel = QtGui.QLabel(self.groupBox2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.eventcounterlabel.sizePolicy().hasHeightForWidth())
        self.eventcounterlabel.setSizePolicy(sizePolicy)
        self.eventcounterlabel.setMinimumSize(QtCore.QSize(1000, 25))
        self.eventcounterlabel.setMaximumSize(QtCore.QSize(3000, 25))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.eventcounterlabel.setFont(font)
        self.eventcounterlabel.setText(_fromUtf8(""))
        self.eventcounterlabel.setObjectName(_fromUtf8("eventcounterlabel"))
        self.gridLayout_5.addWidget(self.eventcounterlabel, 5, 0, 1, 1)
        self.meandtlabel = QtGui.QLabel(self.groupBox2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.meandtlabel.sizePolicy().hasHeightForWidth())
        self.meandtlabel.setSizePolicy(sizePolicy)
        self.meandtlabel.setMinimumSize(QtCore.QSize(1000, 25))
        self.meandtlabel.setMaximumSize(QtCore.QSize(3000, 25))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.meandtlabel.setFont(font)
        self.meandtlabel.setText(_fromUtf8(""))
        self.meandtlabel.setObjectName(_fromUtf8("meandtlabel"))
        self.gridLayout_5.addWidget(self.meandtlabel, 4, 0, 1, 1)
        self.filelabel = QtGui.QLabel(self.groupBox2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.filelabel.sizePolicy().hasHeightForWidth())
        self.filelabel.setSizePolicy(sizePolicy)
        self.filelabel.setMinimumSize(QtCore.QSize(1000, 25))
        self.filelabel.setMaximumSize(QtCore.QSize(3000, 25))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.filelabel.setFont(font)
        self.filelabel.setText(_fromUtf8(""))
        self.filelabel.setObjectName(_fromUtf8("filelabel"))
        self.gridLayout_5.addWidget(self.filelabel, 6, 0, 1, 1)
        self.verticalGroupBox_5 = QtGui.QGroupBox(self.groupBox2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.verticalGroupBox_5.sizePolicy().hasHeightForWidth())
        self.verticalGroupBox_5.setSizePolicy(sizePolicy)
        self.verticalGroupBox_5.setMinimumSize(QtCore.QSize(0, 100))
        self.verticalGroupBox_5.setObjectName(_fromUtf8("verticalGroupBox_5"))
        self.verticalLayout_6 = QtGui.QVBoxLayout(self.verticalGroupBox_5)
        self.verticalLayout_6.setContentsMargins(5, 10, 5, 5)
        self.verticalLayout_6.setObjectName(_fromUtf8("verticalLayout_6"))
        self.gridLayout = QtGui.QGridLayout()
        self.gridLayout.setContentsMargins(5, -1, 5, 5)
        self.gridLayout.setHorizontalSpacing(5)
        self.gridLayout.setVerticalSpacing(0)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.eventnumberentry = QtGui.QLineEdit(self.verticalGroupBox_5)
        self.eventnumberentry.setEnabled(True)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.eventnumberentry.sizePolicy().hasHeightForWidth())
        self.eventnumberentry.setSizePolicy(sizePolicy)
        self.eventnumberentry.setMaximumSize(QtCore.QSize(75, 40))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.eventnumberentry.setFont(font)
        self.eventnumberentry.setObjectName(_fromUtf8("eventnumberentry"))
        self.gridLayout.addWidget(self.eventnumberentry, 0, 3, 1, 1)
        self.previousbutton = QtGui.QPushButton(self.verticalGroupBox_5)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.previousbutton.sizePolicy().hasHeightForWidth())
        self.previousbutton.setSizePolicy(sizePolicy)
        self.previousbutton.setMinimumSize(QtCore.QSize(0, 5))
        self.previousbutton.setMaximumSize(QtCore.QSize(16777215, 40))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.previousbutton.setFont(font)
        self.previousbutton.setObjectName(_fromUtf8("previousbutton"))
        self.gridLayout.addWidget(self.previousbutton, 1, 1, 1, 1)
        self.nextbutton = QtGui.QPushButton(self.verticalGroupBox_5)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.nextbutton.sizePolicy().hasHeightForWidth())
        self.nextbutton.setSizePolicy(sizePolicy)
        self.nextbutton.setMinimumSize(QtCore.QSize(0, 5))
        self.nextbutton.setMaximumSize(QtCore.QSize(16777215, 40))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.nextbutton.setFont(font)
        self.nextbutton.setObjectName(_fromUtf8("nextbutton"))
        self.gridLayout.addWidget(self.nextbutton, 1, 3, 1, 1)
        self.label_4 = QtGui.QLabel(self.verticalGroupBox_5)
        self.label_4.setEnabled(True)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_4.sizePolicy().hasHeightForWidth())
        self.label_4.setSizePolicy(sizePolicy)
        self.label_4.setMaximumSize(QtCore.QSize(16777215, 40))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.label_4.setFont(font)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.gridLayout.addWidget(self.label_4, 0, 1, 1, 2)
        self.gobutton = QtGui.QPushButton(self.verticalGroupBox_5)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.gobutton.sizePolicy().hasHeightForWidth())
        self.gobutton.setSizePolicy(sizePolicy)
        self.gobutton.setMinimumSize(QtCore.QSize(0, 5))
        self.gobutton.setMaximumSize(QtCore.QSize(16777215, 40))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.gobutton.setFont(font)
        self.gobutton.setObjectName(_fromUtf8("gobutton"))
        self.gridLayout.addWidget(self.gobutton, 1, 2, 1, 1)
        self.verticalLayout_6.addLayout(self.gridLayout)
        self.gridLayout_5.addWidget(self.verticalGroupBox_5, 0, 0, 1, 1)
        self.gridLayout_10.addWidget(self.groupBox2, 0, 1, 1, 1)
        self.verticalGroupBox_6 = QtGui.QGroupBox(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.verticalGroupBox_6.sizePolicy().hasHeightForWidth())
        self.verticalGroupBox_6.setSizePolicy(sizePolicy)
        self.verticalGroupBox_6.setMinimumSize(QtCore.QSize(300, 250))
        self.verticalGroupBox_6.setMaximumSize(QtCore.QSize(16777215, 250))
        self.verticalGroupBox_6.setObjectName(_fromUtf8("verticalGroupBox_6"))
        self.verticalLayout_7 = QtGui.QVBoxLayout(self.verticalGroupBox_6)
        self.verticalLayout_7.setContentsMargins(20, 0, 20, 5)
        self.verticalLayout_7.setSpacing(3)
        self.verticalLayout_7.setObjectName(_fromUtf8("verticalLayout_7"))
        self.deleteeventbutton = QtGui.QPushButton(self.verticalGroupBox_6)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Ignored, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.deleteeventbutton.sizePolicy().hasHeightForWidth())
        self.deleteeventbutton.setSizePolicy(sizePolicy)
        self.deleteeventbutton.setMinimumSize(QtCore.QSize(100, 35))
        self.deleteeventbutton.setMaximumSize(QtCore.QSize(16777215, 35))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.deleteeventbutton.setFont(font)
        self.deleteeventbutton.setIconSize(QtCore.QSize(28, 28))
        self.deleteeventbutton.setObjectName(_fromUtf8("deleteeventbutton"))
        self.verticalLayout_7.addWidget(self.deleteeventbutton)
        self.concatenatebutton = QtGui.QPushButton(self.verticalGroupBox_6)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Ignored, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.concatenatebutton.sizePolicy().hasHeightForWidth())
        self.concatenatebutton.setSizePolicy(sizePolicy)
        self.concatenatebutton.setMinimumSize(QtCore.QSize(100, 35))
        self.concatenatebutton.setMaximumSize(QtCore.QSize(16777215, 35))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.concatenatebutton.setFont(font)
        self.concatenatebutton.setIconSize(QtCore.QSize(28, 28))
        self.concatenatebutton.setObjectName(_fromUtf8("concatenatebutton"))
        self.verticalLayout_7.addWidget(self.concatenatebutton)
        self.showcatbutton = QtGui.QPushButton(self.verticalGroupBox_6)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Ignored, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.showcatbutton.sizePolicy().hasHeightForWidth())
        self.showcatbutton.setSizePolicy(sizePolicy)
        self.showcatbutton.setMinimumSize(QtCore.QSize(100, 35))
        self.showcatbutton.setMaximumSize(QtCore.QSize(16777215, 35))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.showcatbutton.setFont(font)
        self.showcatbutton.setIconSize(QtCore.QSize(28, 28))
        self.showcatbutton.setObjectName(_fromUtf8("showcatbutton"))
        self.verticalLayout_7.addWidget(self.showcatbutton)
        self.savecatbutton = QtGui.QPushButton(self.verticalGroupBox_6)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Ignored, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.savecatbutton.sizePolicy().hasHeightForWidth())
        self.savecatbutton.setSizePolicy(sizePolicy)
        self.savecatbutton.setMinimumSize(QtCore.QSize(100, 35))
        self.savecatbutton.setMaximumSize(QtCore.QSize(16777215, 35))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.savecatbutton.setFont(font)
        self.savecatbutton.setIconSize(QtCore.QSize(28, 28))
        self.savecatbutton.setObjectName(_fromUtf8("savecatbutton"))
        self.verticalLayout_7.addWidget(self.savecatbutton)
        self.savefitsbutton = QtGui.QPushButton(self.verticalGroupBox_6)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.savefitsbutton.sizePolicy().hasHeightForWidth())
        self.savefitsbutton.setSizePolicy(sizePolicy)
        self.savefitsbutton.setMinimumSize(QtCore.QSize(100, 35))
        self.savefitsbutton.setMaximumSize(QtCore.QSize(16777215, 35))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(8)
        self.savefitsbutton.setFont(font)
        self.savefitsbutton.setIconSize(QtCore.QSize(28, 28))
        self.savefitsbutton.setObjectName(_fromUtf8("savefitsbutton"))
        self.verticalLayout_7.addWidget(self.savefitsbutton)
        self.savetargetbutton = QtGui.QPushButton(self.verticalGroupBox_6)
        self.savetargetbutton.setMinimumSize(QtCore.QSize(100, 35))
        self.savetargetbutton.setMaximumSize(QtCore.QSize(16777215, 35))
        self.savetargetbutton.setIconSize(QtCore.QSize(28, 28))
        self.savetargetbutton.setObjectName(_fromUtf8("savetargetbutton"))
        self.verticalLayout_7.addWidget(self.savetargetbutton)
        self.gridLayout_10.addWidget(self.verticalGroupBox_6, 0, 2, 1, 1)
        self.groupBox3 = QtGui.QGroupBox(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox3.sizePolicy().hasHeightForWidth())
        self.groupBox3.setSizePolicy(sizePolicy)
        self.groupBox3.setObjectName(_fromUtf8("groupBox3"))
        self.gridLayout_4 = QtGui.QGridLayout(self.groupBox3)
        self.gridLayout_4.setSizeConstraint(QtGui.QLayout.SetMaximumSize)
        self.gridLayout_4.setMargin(10)
        self.gridLayout_4.setVerticalSpacing(10)
        self.gridLayout_4.setObjectName(_fromUtf8("gridLayout_4"))
        self.signalplot = GraphicsLayoutWidget(self.groupBox3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.signalplot.sizePolicy().hasHeightForWidth())
        self.signalplot.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.signalplot.setFont(font)
        self.signalplot.setStyleSheet(_fromUtf8("border-color: rgb(0, 0, 0);"))
        self.signalplot.setFrameShape(QtGui.QFrame.StyledPanel)
        self.signalplot.setObjectName(_fromUtf8("signalplot"))
        self.gridLayout_4.addWidget(self.signalplot, 0, 0, 1, 1)
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setContentsMargins(5, -1, 5, -1)
        self.horizontalLayout_3.setSpacing(20)
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.eventplot = GraphicsLayoutWidget(self.groupBox3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.eventplot.sizePolicy().hasHeightForWidth())
        self.eventplot.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Kozuka Gothic Pro L"))
        font.setPointSize(20)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(3)
        self.eventplot.setFont(font)
        self.eventplot.setStyleSheet(_fromUtf8("font: 25 20pt \"Kozuka Gothic Pro L\";\n"
"border-color: rgb(0, 0, 0);"))
        self.eventplot.setFrameShape(QtGui.QFrame.StyledPanel)
        self.eventplot.setObjectName(_fromUtf8("eventplot"))
        self.horizontalLayout_3.addWidget(self.eventplot)
        self.tabWidget = QtGui.QTabWidget(self.groupBox3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tabWidget.sizePolicy().hasHeightForWidth())
        self.tabWidget.setSizePolicy(sizePolicy)
        self.tabWidget.setMaximumSize(QtCore.QSize(16777215, 16777206))
        self.tabWidget.setTabPosition(QtGui.QTabWidget.East)
        self.tabWidget.setTabShape(QtGui.QTabWidget.Rounded)
        self.tabWidget.setDocumentMode(False)
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.scattertab = QtGui.QWidget()
        self.scattertab.setObjectName(_fromUtf8("scattertab"))
        self.gridLayout_3 = QtGui.QGridLayout(self.scattertab)
        self.gridLayout_3.setMargin(0)
        self.gridLayout_3.setSpacing(0)
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.scatterplot = GraphicsLayoutWidget(self.scattertab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.scatterplot.sizePolicy().hasHeightForWidth())
        self.scatterplot.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Kozuka Gothic Pro L"))
        font.setPointSize(20)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(3)
        self.scatterplot.setFont(font)
        self.scatterplot.setStyleSheet(_fromUtf8("font: 25 20pt \"Kozuka Gothic Pro L\";"))
        self.scatterplot.setObjectName(_fromUtf8("scatterplot"))
        self.gridLayout_3.addWidget(self.scatterplot, 0, 0, 1, 1)
        self.tabWidget.addTab(self.scattertab, _fromUtf8(""))
        self.frachisttab = QtGui.QWidget()
        self.frachisttab.setObjectName(_fromUtf8("frachisttab"))
        self.gridLayout_6 = QtGui.QGridLayout(self.frachisttab)
        self.gridLayout_6.setMargin(0)
        self.gridLayout_6.setSpacing(0)
        self.gridLayout_6.setObjectName(_fromUtf8("gridLayout_6"))
        self.frachistplot = GraphicsLayoutWidget(self.frachisttab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frachistplot.sizePolicy().hasHeightForWidth())
        self.frachistplot.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Kozuka Gothic Pro L"))
        font.setPointSize(20)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(3)
        self.frachistplot.setFont(font)
        self.frachistplot.setStyleSheet(_fromUtf8("font: 25 20pt \"Kozuka Gothic Pro L\";"))
        self.frachistplot.setObjectName(_fromUtf8("frachistplot"))
        self.gridLayout_6.addWidget(self.frachistplot, 0, 0, 1, 1)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.label_7 = QtGui.QLabel(self.frachisttab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_7.sizePolicy().hasHeightForWidth())
        self.label_7.setSizePolicy(sizePolicy)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.horizontalLayout_2.addWidget(self.label_7)
        self.fracbins = QtGui.QLineEdit(self.frachisttab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.fracbins.sizePolicy().hasHeightForWidth())
        self.fracbins.setSizePolicy(sizePolicy)
        self.fracbins.setAlignment(QtCore.Qt.AlignCenter)
        self.fracbins.setObjectName(_fromUtf8("fracbins"))
        self.horizontalLayout_2.addWidget(self.fracbins)
        self.gridLayout_6.addLayout(self.horizontalLayout_2, 1, 0, 1, 1)
        self.tabWidget.addTab(self.frachisttab, _fromUtf8(""))
        self.delitab = QtGui.QWidget()
        self.delitab.setObjectName(_fromUtf8("delitab"))
        self.gridLayout_7 = QtGui.QGridLayout(self.delitab)
        self.gridLayout_7.setMargin(0)
        self.gridLayout_7.setSpacing(0)
        self.gridLayout_7.setObjectName(_fromUtf8("gridLayout_7"))
        self.delihistplot = GraphicsLayoutWidget(self.delitab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.delihistplot.sizePolicy().hasHeightForWidth())
        self.delihistplot.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Kozuka Gothic Pro L"))
        font.setPointSize(20)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(3)
        self.delihistplot.setFont(font)
        self.delihistplot.setStyleSheet(_fromUtf8("font: 25 20pt \"Kozuka Gothic Pro L\";"))
        self.delihistplot.setObjectName(_fromUtf8("delihistplot"))
        self.gridLayout_7.addWidget(self.delihistplot, 0, 0, 1, 1)
        self.horizontalLayout_7 = QtGui.QHBoxLayout()
        self.horizontalLayout_7.setObjectName(_fromUtf8("horizontalLayout_7"))
        self.label_9 = QtGui.QLabel(self.delitab)
        self.label_9.setEnabled(True)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_9.sizePolicy().hasHeightForWidth())
        self.label_9.setSizePolicy(sizePolicy)
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.horizontalLayout_7.addWidget(self.label_9)
        self.delibins = QtGui.QLineEdit(self.delitab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.delibins.sizePolicy().hasHeightForWidth())
        self.delibins.setSizePolicy(sizePolicy)
        self.delibins.setAlignment(QtCore.Qt.AlignCenter)
        self.delibins.setObjectName(_fromUtf8("delibins"))
        self.horizontalLayout_7.addWidget(self.delibins)
        self.horizontalLayout_9 = QtGui.QHBoxLayout()
        self.horizontalLayout_9.setObjectName(_fromUtf8("horizontalLayout_9"))
        self.label_10 = QtGui.QLabel(self.delitab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_10.sizePolicy().hasHeightForWidth())
        self.label_10.setSizePolicy(sizePolicy)
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.horizontalLayout_9.addWidget(self.label_10)
        self.delirange0 = QtGui.QLineEdit(self.delitab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.delirange0.sizePolicy().hasHeightForWidth())
        self.delirange0.setSizePolicy(sizePolicy)
        self.delirange0.setAlignment(QtCore.Qt.AlignCenter)
        self.delirange0.setObjectName(_fromUtf8("delirange0"))
        self.horizontalLayout_9.addWidget(self.delirange0)
        self.label_12 = QtGui.QLabel(self.delitab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_12.sizePolicy().hasHeightForWidth())
        self.label_12.setSizePolicy(sizePolicy)
        self.label_12.setObjectName(_fromUtf8("label_12"))
        self.horizontalLayout_9.addWidget(self.label_12)
        self.delirange1 = QtGui.QLineEdit(self.delitab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.delirange1.sizePolicy().hasHeightForWidth())
        self.delirange1.setSizePolicy(sizePolicy)
        self.delirange1.setAlignment(QtCore.Qt.AlignCenter)
        self.delirange1.setObjectName(_fromUtf8("delirange1"))
        self.horizontalLayout_9.addWidget(self.delirange1)
        self.label_11 = QtGui.QLabel(self.delitab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_11.sizePolicy().hasHeightForWidth())
        self.label_11.setSizePolicy(sizePolicy)
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.horizontalLayout_9.addWidget(self.label_11)
        self.horizontalLayout_7.addLayout(self.horizontalLayout_9)
        self.gridLayout_7.addLayout(self.horizontalLayout_7, 1, 0, 1, 1)
        self.tabWidget.addTab(self.delitab, _fromUtf8(""))
        self.dwelltab = QtGui.QWidget()
        self.dwelltab.setObjectName(_fromUtf8("dwelltab"))
        self.gridLayout_8 = QtGui.QGridLayout(self.dwelltab)
        self.gridLayout_8.setMargin(0)
        self.gridLayout_8.setSpacing(0)
        self.gridLayout_8.setObjectName(_fromUtf8("gridLayout_8"))
        self.dwellhistplot = GraphicsLayoutWidget(self.dwelltab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.dwellhistplot.sizePolicy().hasHeightForWidth())
        self.dwellhistplot.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Kozuka Gothic Pro L"))
        font.setPointSize(20)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(3)
        self.dwellhistplot.setFont(font)
        self.dwellhistplot.setStyleSheet(_fromUtf8("font: 25 20pt \"Kozuka Gothic Pro L\";"))
        self.dwellhistplot.setObjectName(_fromUtf8("dwellhistplot"))
        self.gridLayout_8.addWidget(self.dwellhistplot, 0, 0, 1, 1)
        self.horizontalLayout_14 = QtGui.QHBoxLayout()
        self.horizontalLayout_14.setObjectName(_fromUtf8("horizontalLayout_14"))
        self.label_21 = QtGui.QLabel(self.dwelltab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_21.sizePolicy().hasHeightForWidth())
        self.label_21.setSizePolicy(sizePolicy)
        self.label_21.setObjectName(_fromUtf8("label_21"))
        self.horizontalLayout_14.addWidget(self.label_21)
        self.dwellbins = QtGui.QLineEdit(self.dwelltab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.dwellbins.sizePolicy().hasHeightForWidth())
        self.dwellbins.setSizePolicy(sizePolicy)
        self.dwellbins.setAlignment(QtCore.Qt.AlignCenter)
        self.dwellbins.setObjectName(_fromUtf8("dwellbins"))
        self.horizontalLayout_14.addWidget(self.dwellbins)
        self.horizontalLayout_10 = QtGui.QHBoxLayout()
        self.horizontalLayout_10.setObjectName(_fromUtf8("horizontalLayout_10"))
        self.label_22 = QtGui.QLabel(self.dwelltab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_22.sizePolicy().hasHeightForWidth())
        self.label_22.setSizePolicy(sizePolicy)
        self.label_22.setObjectName(_fromUtf8("label_22"))
        self.horizontalLayout_10.addWidget(self.label_22)
        self.dwellrange0 = QtGui.QLineEdit(self.dwelltab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.dwellrange0.sizePolicy().hasHeightForWidth())
        self.dwellrange0.setSizePolicy(sizePolicy)
        self.dwellrange0.setAlignment(QtCore.Qt.AlignCenter)
        self.dwellrange0.setObjectName(_fromUtf8("dwellrange0"))
        self.horizontalLayout_10.addWidget(self.dwellrange0)
        self.label_23 = QtGui.QLabel(self.dwelltab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_23.sizePolicy().hasHeightForWidth())
        self.label_23.setSizePolicy(sizePolicy)
        self.label_23.setObjectName(_fromUtf8("label_23"))
        self.horizontalLayout_10.addWidget(self.label_23)
        self.dwellrange1 = QtGui.QLineEdit(self.dwelltab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.dwellrange1.sizePolicy().hasHeightForWidth())
        self.dwellrange1.setSizePolicy(sizePolicy)
        self.dwellrange1.setAlignment(QtCore.Qt.AlignCenter)
        self.dwellrange1.setObjectName(_fromUtf8("dwellrange1"))
        self.horizontalLayout_10.addWidget(self.dwellrange1)
        self.label_24 = QtGui.QLabel(self.dwelltab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_24.sizePolicy().hasHeightForWidth())
        self.label_24.setSizePolicy(sizePolicy)
        self.label_24.setObjectName(_fromUtf8("label_24"))
        self.horizontalLayout_10.addWidget(self.label_24)
        self.horizontalLayout_14.addLayout(self.horizontalLayout_10)
        self.gridLayout_8.addLayout(self.horizontalLayout_14, 1, 0, 1, 1)
        self.tabWidget.addTab(self.dwelltab, _fromUtf8(""))
        self.dttab = QtGui.QWidget()
        self.dttab.setObjectName(_fromUtf8("dttab"))
        self.gridLayout_9 = QtGui.QGridLayout(self.dttab)
        self.gridLayout_9.setMargin(0)
        self.gridLayout_9.setSpacing(0)
        self.gridLayout_9.setObjectName(_fromUtf8("gridLayout_9"))
        self.dthistplot = GraphicsLayoutWidget(self.dttab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.dthistplot.sizePolicy().hasHeightForWidth())
        self.dthistplot.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Kozuka Gothic Pro L"))
        font.setPointSize(20)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(3)
        self.dthistplot.setFont(font)
        self.dthistplot.setStyleSheet(_fromUtf8("font: 25 20pt \"Kozuka Gothic Pro L\";"))
        self.dthistplot.setObjectName(_fromUtf8("dthistplot"))
        self.gridLayout_9.addWidget(self.dthistplot, 0, 0, 1, 1)
        self.horizontalLayout_18 = QtGui.QHBoxLayout()
        self.horizontalLayout_18.setObjectName(_fromUtf8("horizontalLayout_18"))
        self.label_25 = QtGui.QLabel(self.dttab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_25.sizePolicy().hasHeightForWidth())
        self.label_25.setSizePolicy(sizePolicy)
        self.label_25.setObjectName(_fromUtf8("label_25"))
        self.horizontalLayout_18.addWidget(self.label_25)
        self.dtbins = QtGui.QLineEdit(self.dttab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.dtbins.sizePolicy().hasHeightForWidth())
        self.dtbins.setSizePolicy(sizePolicy)
        self.dtbins.setAlignment(QtCore.Qt.AlignCenter)
        self.dtbins.setObjectName(_fromUtf8("dtbins"))
        self.horizontalLayout_18.addWidget(self.dtbins)
        self.horizontalLayout_19 = QtGui.QHBoxLayout()
        self.horizontalLayout_19.setObjectName(_fromUtf8("horizontalLayout_19"))
        self.label_26 = QtGui.QLabel(self.dttab)
        self.label_26.setObjectName(_fromUtf8("label_26"))
        self.horizontalLayout_19.addWidget(self.label_26)
        self.dtrange0 = QtGui.QLineEdit(self.dttab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.dtrange0.sizePolicy().hasHeightForWidth())
        self.dtrange0.setSizePolicy(sizePolicy)
        self.dtrange0.setAlignment(QtCore.Qt.AlignCenter)
        self.dtrange0.setObjectName(_fromUtf8("dtrange0"))
        self.horizontalLayout_19.addWidget(self.dtrange0)
        self.label_27 = QtGui.QLabel(self.dttab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_27.sizePolicy().hasHeightForWidth())
        self.label_27.setSizePolicy(sizePolicy)
        self.label_27.setObjectName(_fromUtf8("label_27"))
        self.horizontalLayout_19.addWidget(self.label_27)
        self.dtrange1 = QtGui.QLineEdit(self.dttab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.dtrange1.sizePolicy().hasHeightForWidth())
        self.dtrange1.setSizePolicy(sizePolicy)
        self.dtrange1.setAlignment(QtCore.Qt.AlignCenter)
        self.dtrange1.setObjectName(_fromUtf8("dtrange1"))
        self.horizontalLayout_19.addWidget(self.dtrange1)
        self.label_28 = QtGui.QLabel(self.dttab)
        self.label_28.setObjectName(_fromUtf8("label_28"))
        self.horizontalLayout_19.addWidget(self.label_28)
        self.horizontalLayout_18.addLayout(self.horizontalLayout_19)
        self.gridLayout_9.addLayout(self.horizontalLayout_18, 1, 0, 1, 1)
        self.tabWidget.addTab(self.dttab, _fromUtf8(""))
        self.horizontalLayout_3.addWidget(self.tabWidget)
        self.gridLayout_4.addLayout(self.horizontalLayout_3, 1, 0, 1, 1)
        self.eventinfolabel = QtGui.QLabel(self.groupBox3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.eventinfolabel.sizePolicy().hasHeightForWidth())
        self.eventinfolabel.setSizePolicy(sizePolicy)
        self.eventinfolabel.setMinimumSize(QtCore.QSize(500, 25))
        self.eventinfolabel.setMaximumSize(QtCore.QSize(3000, 25))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.eventinfolabel.setFont(font)
        self.eventinfolabel.setText(_fromUtf8(""))
        self.eventinfolabel.setObjectName(_fromUtf8("eventinfolabel"))
        self.gridLayout_4.addWidget(self.eventinfolabel, 2, 0, 1, 1)
        self.gridLayout_10.addWidget(self.groupBox3, 1, 0, 1, 3)
        PythIon.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(PythIon)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1952, 36))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        self.menuFile = QtGui.QMenu(self.menubar)
        self.menuFile.setObjectName(_fromUtf8("menuFile"))
        self.menuEdit = QtGui.QMenu(self.menubar)
        self.menuEdit.setObjectName(_fromUtf8("menuEdit"))
        PythIon.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(PythIon)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        PythIon.setStatusBar(self.statusbar)
        self.actionInvert = QtGui.QAction(PythIon)
        self.actionInvert.setObjectName(_fromUtf8("actionInvert"))
        self.actionsetbuffer = QtGui.QAction(PythIon)
        self.actionsetbuffer.setObjectName(_fromUtf8("actionsetbuffer"))
        self.Poresizeraction = QtGui.QAction(PythIon)
        self.Poresizeraction.setObjectName(_fromUtf8("Poresizeraction"))
        self.actionBatch_Process = QtGui.QAction(PythIon)
        self.actionBatch_Process.setObjectName(_fromUtf8("actionBatch_Process"))
        self.menuFile.addAction(self.Poresizeraction)
        self.menuFile.addAction(self.actionBatch_Process)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuEdit.menuAction())

        self.retranslateUi(PythIon)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(PythIon)

    def retranslateUi(self, PythIon):
        PythIon.setWindowTitle(_translate("PythIon", "PythIon", None))
        self.previousfilebutton.setText(_translate("PythIon", "PREVIOUS", None))
        self.loaddatabutton.setText(_translate("PythIon", "LOAD DATA", None))
        self.cutbutton.setText(_translate("PythIon", "CUT", None))
        self.nextfilebutton.setText(_translate("PythIon", "NEXT", None))
        self.loadbutton.setText(_translate("PythIon", "LOAD", None))
        self.clearscatterbutton.setText(_translate("PythIon", "CLEAR DATA", None))
        self.invertbutton.setText(_translate("PythIon", "INVERT", None))
        self.analyzebutton.setText(_translate("PythIon", "ANALYZE", None))
        self.baselinebutton.setText(_translate("PythIon", "BASELINE", None))
        self.fitbutton.setText(_translate("PythIon", "FIT", None))
        self.label.setText(_translate("PythIon", "Low Pass Filter (kHz)", None))
        self.label_2.setText(_translate("PythIon", "Output Samplerate (kHz)", None))
        self.label_5.setText(_translate("PythIon", "Event Buffer (samples)", None))
        self.label_3.setText(_translate("PythIon", "Threshold (nA)", None))
        self.label_6.setText(_translate("PythIon", "Level Threshold (nA)", None))
        self.LPentry.setText(_translate("PythIon", "100", None))
        self.outputsamplerateentry.setText(_translate("PythIon", "4166.67", None))
        self.eventbufferentry.setText(_translate("PythIon", "1000", None))
        self.thresholdentry.setText(_translate("PythIon", ".3", None))
        self.levelthresholdentry.setText(_translate("PythIon", "None", None))
        self.eventnumberentry.setText(_translate("PythIon", "0", None))
        self.previousbutton.setText(_translate("PythIon", "Previous", None))
        self.nextbutton.setText(_translate("PythIon", "Next", None))
        self.label_4.setText(_translate("PythIon", "Enter Event Number To View", None))
        self.gobutton.setText(_translate("PythIon", "Go", None))
        self.deleteeventbutton.setText(_translate("PythIon", "DELETE EVENT", None))
        self.concatenatebutton.setText(_translate("PythIon", "CONCATENATE", None))
        self.showcatbutton.setText(_translate("PythIon", "SHOW CAT. TRACE", None))
        self.savecatbutton.setText(_translate("PythIon", "SAVE CAT. TRACE", None))
        self.savefitsbutton.setText(_translate("PythIon", "SAVE EVENT FITS", None))
        self.savetargetbutton.setText(_translate("PythIon", "SAVE TARGET", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.scattertab), _translate("PythIon", "Scatter", None))
        self.label_7.setText(_translate("PythIon", "Bins:", None))
        self.fracbins.setText(_translate("PythIon", "50", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.frachisttab), _translate("PythIon", "Frac", None))
        self.label_9.setText(_translate("PythIon", "Bins", None))
        self.delibins.setText(_translate("PythIon", "50", None))
        self.label_10.setText(_translate("PythIon", "(", None))
        self.delirange0.setText(_translate("PythIon", "0", None))
        self.label_12.setText(_translate("PythIon", "-", None))
        self.delirange1.setText(_translate("PythIon", "1", None))
        self.label_11.setText(_translate("PythIon", ")", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.delitab), _translate("PythIon", "Deli", None))
        self.label_21.setText(_translate("PythIon", "Bins", None))
        self.dwellbins.setText(_translate("PythIon", "100", None))
        self.label_22.setText(_translate("PythIon", "(", None))
        self.dwellrange0.setText(_translate("PythIon", "0", None))
        self.label_23.setText(_translate("PythIon", "-", None))
        self.dwellrange1.setText(_translate("PythIon", "5", None))
        self.label_24.setText(_translate("PythIon", ")", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.dwelltab), _translate("PythIon", "Dwell", None))
        self.label_25.setText(_translate("PythIon", "Bins", None))
        self.dtbins.setText(_translate("PythIon", "100", None))
        self.label_26.setText(_translate("PythIon", "(", None))
        self.dtrange0.setText(_translate("PythIon", "0", None))
        self.label_27.setText(_translate("PythIon", "-", None))
        self.dtrange1.setText(_translate("PythIon", "1", None))
        self.label_28.setText(_translate("PythIon", ")", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.dttab), _translate("PythIon", "dt", None))
        self.menuFile.setTitle(_translate("PythIon", "File", None))
        self.menuEdit.setTitle(_translate("PythIon", "Edit", None))
        self.actionInvert.setText(_translate("PythIon", "Invert data", None))
        self.actionsetbuffer.setText(_translate("PythIon", "Set Event Buffer Size", None))
        self.Poresizeraction.setText(_translate("PythIon", "PoreSizer", None))
        self.actionBatch_Process.setText(_translate("PythIon", "Batch Process", None))

from pyqtgraph import GraphicsLayoutWidget
