# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'PlotGUItest.ui'
#
# Created: Thu Oct 02 18:01:31 2014
#      by: PyQt4 UI code generator 4.9.6
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(1129, 707)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setAutoFillBackground(False)
        self.centralwidget = QtGui.QWidget(MainWindow)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.centralwidget.sizePolicy().hasHeightForWidth())
        self.centralwidget.setSizePolicy(sizePolicy)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.verticalLayoutWidget = QtGui.QWidget(self.centralwidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(0, 113, 1121, 251))
        self.verticalLayoutWidget.setObjectName(_fromUtf8("verticalLayoutWidget"))
        self.verticalLayout = QtGui.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setSizeConstraint(QtGui.QLayout.SetDefaultConstraint)
        self.verticalLayout.setMargin(0)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.signalplot = GraphicsLayoutWidget(self.verticalLayoutWidget)
        self.signalplot.setObjectName(_fromUtf8("signalplot"))
        self.verticalLayout.addWidget(self.signalplot)
        self.horizontalLayoutWidget = QtGui.QWidget(self.centralwidget)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(0, 0, 421, 111))
        self.horizontalLayoutWidget.setObjectName(_fromUtf8("horizontalLayoutWidget"))
        self.horizontalLayout_2 = QtGui.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout_2.setMargin(0)
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.verticalLayout_3 = QtGui.QVBoxLayout()
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.loadbutton = QtGui.QPushButton(self.horizontalLayoutWidget)
        self.loadbutton.setObjectName(_fromUtf8("loadbutton"))
        self.verticalLayout_3.addWidget(self.loadbutton)
        self.cutbutton = QtGui.QPushButton(self.horizontalLayoutWidget)
        self.cutbutton.setObjectName(_fromUtf8("cutbutton"))
        self.verticalLayout_3.addWidget(self.cutbutton)
        self.baselinebutton = QtGui.QPushButton(self.horizontalLayoutWidget)
        self.baselinebutton.setObjectName(_fromUtf8("baselinebutton"))
        self.verticalLayout_3.addWidget(self.baselinebutton)
        self.analyzebutton = QtGui.QPushButton(self.horizontalLayoutWidget)
        self.analyzebutton.setObjectName(_fromUtf8("analyzebutton"))
        self.verticalLayout_3.addWidget(self.analyzebutton)
        self.savebutton = QtGui.QPushButton(self.horizontalLayoutWidget)
        self.savebutton.setObjectName(_fromUtf8("savebutton"))
        self.verticalLayout_3.addWidget(self.savebutton)
        self.horizontalLayout_2.addLayout(self.verticalLayout_3)
        self.verticalLayout_5 = QtGui.QVBoxLayout()
        self.verticalLayout_5.setObjectName(_fromUtf8("verticalLayout_5"))
        self.label = QtGui.QLabel(self.horizontalLayoutWidget)
        self.label.setObjectName(_fromUtf8("label"))
        self.verticalLayout_5.addWidget(self.label)
        self.label_2 = QtGui.QLabel(self.horizontalLayoutWidget)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.verticalLayout_5.addWidget(self.label_2)
        self.label_3 = QtGui.QLabel(self.horizontalLayoutWidget)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.verticalLayout_5.addWidget(self.label_3)
        self.horizontalLayout_2.addLayout(self.verticalLayout_5)
        self.verticalLayout_4 = QtGui.QVBoxLayout()
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.LPentry = QtGui.QLineEdit(self.horizontalLayoutWidget)
        self.LPentry.setObjectName(_fromUtf8("LPentry"))
        self.verticalLayout_4.addWidget(self.LPentry)
        self.outputsamplerateentry = QtGui.QLineEdit(self.horizontalLayoutWidget)
        self.outputsamplerateentry.setObjectName(_fromUtf8("outputsamplerateentry"))
        self.verticalLayout_4.addWidget(self.outputsamplerateentry)
        self.thresholdentry = QtGui.QLineEdit(self.horizontalLayoutWidget)
        self.thresholdentry.setObjectName(_fromUtf8("thresholdentry"))
        self.verticalLayout_4.addWidget(self.thresholdentry)
        self.horizontalLayout_2.addLayout(self.verticalLayout_4)
        self.verticalLayoutWidget_5 = QtGui.QWidget(self.centralwidget)
        self.verticalLayoutWidget_5.setGeometry(QtCore.QRect(429, 60, 691, 34))
        self.verticalLayoutWidget_5.setObjectName(_fromUtf8("verticalLayoutWidget_5"))
        self.verticalLayout_6 = QtGui.QVBoxLayout(self.verticalLayoutWidget_5)
        self.verticalLayout_6.setMargin(0)
        self.verticalLayout_6.setObjectName(_fromUtf8("verticalLayout_6"))
        self.eventcounterlabel = QtGui.QLabel(self.verticalLayoutWidget_5)
        self.eventcounterlabel.setText(_fromUtf8(""))
        self.eventcounterlabel.setObjectName(_fromUtf8("eventcounterlabel"))
        self.verticalLayout_6.addWidget(self.eventcounterlabel)
        self.filelabel = QtGui.QLabel(self.verticalLayoutWidget_5)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.filelabel.sizePolicy().hasHeightForWidth())
        self.filelabel.setSizePolicy(sizePolicy)
        self.filelabel.setText(_fromUtf8(""))
        self.filelabel.setObjectName(_fromUtf8("filelabel"))
        self.verticalLayout_6.addWidget(self.filelabel)
        self.horizontalLayoutWidget_2 = QtGui.QWidget(self.centralwidget)
        self.horizontalLayoutWidget_2.setGeometry(QtCore.QRect(0, 370, 1121, 280))
        self.horizontalLayoutWidget_2.setObjectName(_fromUtf8("horizontalLayoutWidget_2"))
        self.horizontalLayout_3 = QtGui.QHBoxLayout(self.horizontalLayoutWidget_2)
        self.horizontalLayout_3.setMargin(0)
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.eventplot = PlotWidget(self.horizontalLayoutWidget_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.eventplot.sizePolicy().hasHeightForWidth())
        self.eventplot.setSizePolicy(sizePolicy)
        self.eventplot.setStyleSheet(_fromUtf8("font: 25 20pt \"Kozuka Gothic Pro L\";"))
        self.eventplot.setObjectName(_fromUtf8("eventplot"))
        self.horizontalLayout_3.addWidget(self.eventplot)
        self.scatterplot = PlotWidget(self.horizontalLayoutWidget_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.scatterplot.sizePolicy().hasHeightForWidth())
        self.scatterplot.setSizePolicy(sizePolicy)
        self.scatterplot.setStyleSheet(_fromUtf8("font: 25 20pt \"Kozuka Gothic Pro L\";"))
        self.scatterplot.setObjectName(_fromUtf8("scatterplot"))
        self.horizontalLayout_3.addWidget(self.scatterplot)
        self.horizontalLayoutWidget_3 = QtGui.QWidget(self.centralwidget)
        self.horizontalLayoutWidget_3.setGeometry(QtCore.QRect(650, 30, 239, 25))
        self.horizontalLayoutWidget_3.setObjectName(_fromUtf8("horizontalLayoutWidget_3"))
        self.horizontalLayout_4 = QtGui.QHBoxLayout(self.horizontalLayoutWidget_3)
        self.horizontalLayout_4.setMargin(0)
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.previousbutton = QtGui.QPushButton(self.horizontalLayoutWidget_3)
        self.previousbutton.setObjectName(_fromUtf8("previousbutton"))
        self.horizontalLayout_4.addWidget(self.previousbutton)
        self.gobutton = QtGui.QPushButton(self.horizontalLayoutWidget_3)
        self.gobutton.setObjectName(_fromUtf8("gobutton"))
        self.horizontalLayout_4.addWidget(self.gobutton)
        self.nextbutton = QtGui.QPushButton(self.horizontalLayoutWidget_3)
        self.nextbutton.setObjectName(_fromUtf8("nextbutton"))
        self.horizontalLayout_4.addWidget(self.nextbutton)
        self.horizontalLayoutWidget_4 = QtGui.QWidget(self.centralwidget)
        self.horizontalLayoutWidget_4.setGeometry(QtCore.QRect(650, 0, 241, 22))
        self.horizontalLayoutWidget_4.setObjectName(_fromUtf8("horizontalLayoutWidget_4"))
        self.horizontalLayout_5 = QtGui.QHBoxLayout(self.horizontalLayoutWidget_4)
        self.horizontalLayout_5.setMargin(0)
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        self.label_4 = QtGui.QLabel(self.horizontalLayoutWidget_4)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.horizontalLayout_5.addWidget(self.label_4)
        self.eventnumberentry = QtGui.QLineEdit(self.horizontalLayoutWidget_4)
        self.eventnumberentry.setObjectName(_fromUtf8("eventnumberentry"))
        self.horizontalLayout_5.addWidget(self.eventnumberentry)
        self.verticalLayoutWidget_6 = QtGui.QWidget(self.centralwidget)
        self.verticalLayoutWidget_6.setGeometry(QtCore.QRect(960, 0, 101, 54))
        self.verticalLayoutWidget_6.setObjectName(_fromUtf8("verticalLayoutWidget_6"))
        self.verticalLayout_7 = QtGui.QVBoxLayout(self.verticalLayoutWidget_6)
        self.verticalLayout_7.setMargin(0)
        self.verticalLayout_7.setObjectName(_fromUtf8("verticalLayout_7"))
        self.deleteeventbutton = QtGui.QPushButton(self.verticalLayoutWidget_6)
        self.deleteeventbutton.setObjectName(_fromUtf8("deleteeventbutton"))
        self.verticalLayout_7.addWidget(self.deleteeventbutton)
        self.clearscatterbutton = QtGui.QPushButton(self.verticalLayoutWidget_6)
        self.clearscatterbutton.setObjectName(_fromUtf8("clearscatterbutton"))
        self.verticalLayout_7.addWidget(self.clearscatterbutton)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1129, 21))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)
        self.toolBar = QtGui.QToolBar(MainWindow)
        self.toolBar.setObjectName(_fromUtf8("toolBar"))
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow", None))
        self.loadbutton.setText(_translate("MainWindow", "LOAD", None))
        self.cutbutton.setText(_translate("MainWindow", "CUT", None))
        self.baselinebutton.setText(_translate("MainWindow", "BASELINE CALC", None))
        self.analyzebutton.setText(_translate("MainWindow", "ANALYZE", None))
        self.savebutton.setText(_translate("MainWindow", "SAVE", None))
        self.label.setText(_translate("MainWindow", "Low Pass Filter (kHz)", None))
        self.label_2.setText(_translate("MainWindow", "Output Samplerate (kHz)", None))
        self.label_3.setText(_translate("MainWindow", "Threshold (nA)", None))
        self.LPentry.setText(_translate("MainWindow", "100", None))
        self.outputsamplerateentry.setText(_translate("MainWindow", "4166.67", None))
        self.thresholdentry.setText(_translate("MainWindow", ".8", None))
        self.previousbutton.setText(_translate("MainWindow", "Previous", None))
        self.gobutton.setText(_translate("MainWindow", "Go", None))
        self.nextbutton.setText(_translate("MainWindow", "Next", None))
        self.label_4.setText(_translate("MainWindow", "Enter Event Number To View", None))
        self.eventnumberentry.setText(_translate("MainWindow", "0", None))
        self.deleteeventbutton.setText(_translate("MainWindow", "DELETE EVENT", None))
        self.clearscatterbutton.setText(_translate("MainWindow", "CLEAR SCATTER", None))
        self.toolBar.setWindowTitle(_translate("MainWindow", "toolBar", None))

from pyqtgraph import GraphicsLayoutWidget, PlotWidget
