# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'plotguiuniversal.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_PythIon(object):
    def setupUi(self, PythIon):
        PythIon.setObjectName("PythIon")
        PythIon.resize(1254, 730)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(PythIon.sizePolicy().hasHeightForWidth())
        PythIon.setSizePolicy(sizePolicy)
        PythIon.setMinimumSize(QtCore.QSize(0, 500))
        PythIon.setMaximumSize(QtCore.QSize(16777215, 800))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../../../Downloads/PythIon/pythionlogo.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        PythIon.setWindowIcon(icon)
        PythIon.setAutoFillBackground(False)
        PythIon.setDockNestingEnabled(True)
        self.centralwidget = QtWidgets.QWidget(PythIon)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.centralwidget.sizePolicy().hasHeightForWidth())
        self.centralwidget.setSizePolicy(sizePolicy)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_10 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_10.setContentsMargins(10, 5, 10, 5)
        self.gridLayout_10.setHorizontalSpacing(15)
        self.gridLayout_10.setVerticalSpacing(10)
        self.gridLayout_10.setObjectName("gridLayout_10")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setSizeConstraint(QtWidgets.QLayout.SetMaximumSize)
        self.horizontalLayout_4.setSpacing(10)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox.sizePolicy().hasHeightForWidth())
        self.groupBox.setSizePolicy(sizePolicy)
        self.groupBox.setMinimumSize(QtCore.QSize(175, 0))
        self.groupBox.setMaximumSize(QtCore.QSize(175, 150))
        self.groupBox.setAlignment(QtCore.Qt.AlignCenter)
        self.groupBox.setObjectName("groupBox")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.groupBox)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.loadbutton = QtWidgets.QPushButton(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.loadbutton.sizePolicy().hasHeightForWidth())
        self.loadbutton.setSizePolicy(sizePolicy)
        self.loadbutton.setMinimumSize(QtCore.QSize(70, 0))
        self.loadbutton.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.loadbutton.setFont(font)
        self.loadbutton.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.loadbutton.setAutoFillBackground(False)
        self.loadbutton.setObjectName("loadbutton")
        self.gridLayout_2.addWidget(self.loadbutton, 0, 0, 1, 1)
        self.cutbutton = QtWidgets.QPushButton(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cutbutton.sizePolicy().hasHeightForWidth())
        self.cutbutton.setSizePolicy(sizePolicy)
        self.cutbutton.setMinimumSize(QtCore.QSize(70, 5))
        self.cutbutton.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.cutbutton.setFont(font)
        self.cutbutton.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.cutbutton.setAutoFillBackground(False)
        self.cutbutton.setObjectName("cutbutton")
        self.gridLayout_2.addWidget(self.cutbutton, 0, 1, 1, 1)
        self.nextfilebutton = QtWidgets.QPushButton(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.nextfilebutton.sizePolicy().hasHeightForWidth())
        self.nextfilebutton.setSizePolicy(sizePolicy)
        self.nextfilebutton.setMinimumSize(QtCore.QSize(70, 0))
        self.nextfilebutton.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.nextfilebutton.setFont(font)
        self.nextfilebutton.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.nextfilebutton.setAutoFillBackground(False)
        self.nextfilebutton.setObjectName("nextfilebutton")
        self.gridLayout_2.addWidget(self.nextfilebutton, 1, 0, 1, 1)
        self.baselinebutton = QtWidgets.QPushButton(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.baselinebutton.sizePolicy().hasHeightForWidth())
        self.baselinebutton.setSizePolicy(sizePolicy)
        self.baselinebutton.setMinimumSize(QtCore.QSize(70, 0))
        self.baselinebutton.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.baselinebutton.setFont(font)
        self.baselinebutton.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.baselinebutton.setAutoFillBackground(False)
        self.baselinebutton.setObjectName("baselinebutton")
        self.gridLayout_2.addWidget(self.baselinebutton, 1, 1, 1, 1)
        self.previousfilebutton = QtWidgets.QPushButton(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.previousfilebutton.sizePolicy().hasHeightForWidth())
        self.previousfilebutton.setSizePolicy(sizePolicy)
        self.previousfilebutton.setMinimumSize(QtCore.QSize(70, 0))
        self.previousfilebutton.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.previousfilebutton.setFont(font)
        self.previousfilebutton.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.previousfilebutton.setAutoFillBackground(False)
        self.previousfilebutton.setObjectName("previousfilebutton")
        self.gridLayout_2.addWidget(self.previousfilebutton, 2, 0, 1, 1)
        self.analyzebutton = QtWidgets.QPushButton(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.analyzebutton.sizePolicy().hasHeightForWidth())
        self.analyzebutton.setSizePolicy(sizePolicy)
        self.analyzebutton.setMinimumSize(QtCore.QSize(70, 0))
        self.analyzebutton.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.analyzebutton.setFont(font)
        self.analyzebutton.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.analyzebutton.setAutoFillBackground(False)
        self.analyzebutton.setObjectName("analyzebutton")
        self.gridLayout_2.addWidget(self.analyzebutton, 2, 1, 1, 1)
        self.invertbutton = QtWidgets.QPushButton(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.invertbutton.sizePolicy().hasHeightForWidth())
        self.invertbutton.setSizePolicy(sizePolicy)
        self.invertbutton.setMinimumSize(QtCore.QSize(70, 0))
        self.invertbutton.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.invertbutton.setFont(font)
        self.invertbutton.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.invertbutton.setAutoFillBackground(False)
        self.invertbutton.setObjectName("invertbutton")
        self.gridLayout_2.addWidget(self.invertbutton, 3, 0, 1, 1)
        self.fitbutton = QtWidgets.QPushButton(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.fitbutton.sizePolicy().hasHeightForWidth())
        self.fitbutton.setSizePolicy(sizePolicy)
        self.fitbutton.setMinimumSize(QtCore.QSize(70, 0))
        self.fitbutton.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.fitbutton.setFont(font)
        self.fitbutton.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.fitbutton.setAutoFillBackground(False)
        self.fitbutton.setObjectName("fitbutton")
        self.gridLayout_2.addWidget(self.fitbutton, 3, 1, 1, 1)
        self.clearscatterbutton = QtWidgets.QPushButton(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.clearscatterbutton.sizePolicy().hasHeightForWidth())
        self.clearscatterbutton.setSizePolicy(sizePolicy)
        self.clearscatterbutton.setMinimumSize(QtCore.QSize(70, 5))
        self.clearscatterbutton.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.clearscatterbutton.setFont(font)
        self.clearscatterbutton.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.clearscatterbutton.setAutoFillBackground(False)
        self.clearscatterbutton.setObjectName("clearscatterbutton")
        self.gridLayout_2.addWidget(self.clearscatterbutton, 4, 0, 1, 1)
        self.loaddatabutton = QtWidgets.QPushButton(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.loaddatabutton.sizePolicy().hasHeightForWidth())
        self.loaddatabutton.setSizePolicy(sizePolicy)
        self.loaddatabutton.setMinimumSize(QtCore.QSize(70, 0))
        self.loaddatabutton.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.loaddatabutton.setFont(font)
        self.loaddatabutton.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.loaddatabutton.setAutoFillBackground(False)
        self.loaddatabutton.setObjectName("loaddatabutton")
        self.gridLayout_2.addWidget(self.loaddatabutton, 4, 1, 1, 1)
        self.horizontalLayout_4.addWidget(self.groupBox)
        self.groupBox1 = QtWidgets.QGroupBox(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox1.sizePolicy().hasHeightForWidth())
        self.groupBox1.setSizePolicy(sizePolicy)
        self.groupBox1.setMinimumSize(QtCore.QSize(250, 5))
        self.groupBox1.setMaximumSize(QtCore.QSize(250, 150))
        self.groupBox1.setObjectName("groupBox1")
        self.formLayout = QtWidgets.QFormLayout(self.groupBox1)
        self.formLayout.setContentsMargins(0, 0, 0, 0)
        self.formLayout.setObjectName("formLayout")
        self.label = QtWidgets.QLabel(self.groupBox1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setMinimumSize(QtCore.QSize(125, 0))
        self.label.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label)
        self.LPentry = QtWidgets.QLineEdit(self.groupBox1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.LPentry.sizePolicy().hasHeightForWidth())
        self.LPentry.setSizePolicy(sizePolicy)
        self.LPentry.setMinimumSize(QtCore.QSize(60, 0))
        self.LPentry.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.LPentry.setFont(font)
        self.LPentry.setAlignment(QtCore.Qt.AlignCenter)
        self.LPentry.setObjectName("LPentry")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.LPentry)
        self.label_2 = QtWidgets.QLabel(self.groupBox1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_2.sizePolicy().hasHeightForWidth())
        self.label_2.setSizePolicy(sizePolicy)
        self.label_2.setMinimumSize(QtCore.QSize(125, 0))
        self.label_2.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_2)
        self.outputsamplerateentry = QtWidgets.QLineEdit(self.groupBox1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.outputsamplerateentry.sizePolicy().hasHeightForWidth())
        self.outputsamplerateentry.setSizePolicy(sizePolicy)
        self.outputsamplerateentry.setMinimumSize(QtCore.QSize(60, 0))
        self.outputsamplerateentry.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.outputsamplerateentry.setFont(font)
        self.outputsamplerateentry.setAlignment(QtCore.Qt.AlignCenter)
        self.outputsamplerateentry.setObjectName("outputsamplerateentry")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.outputsamplerateentry)
        self.label_5 = QtWidgets.QLabel(self.groupBox1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_5.sizePolicy().hasHeightForWidth())
        self.label_5.setSizePolicy(sizePolicy)
        self.label_5.setMinimumSize(QtCore.QSize(125, 0))
        self.label_5.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_5)
        self.eventbufferentry = QtWidgets.QLineEdit(self.groupBox1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.eventbufferentry.sizePolicy().hasHeightForWidth())
        self.eventbufferentry.setSizePolicy(sizePolicy)
        self.eventbufferentry.setMinimumSize(QtCore.QSize(60, 0))
        self.eventbufferentry.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.eventbufferentry.setFont(font)
        self.eventbufferentry.setAlignment(QtCore.Qt.AlignCenter)
        self.eventbufferentry.setObjectName("eventbufferentry")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.eventbufferentry)
        self.label_3 = QtWidgets.QLabel(self.groupBox1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_3.sizePolicy().hasHeightForWidth())
        self.label_3.setSizePolicy(sizePolicy)
        self.label_3.setMinimumSize(QtCore.QSize(125, 0))
        self.label_3.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_3)
        self.thresholdentry = QtWidgets.QLineEdit(self.groupBox1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.thresholdentry.sizePolicy().hasHeightForWidth())
        self.thresholdentry.setSizePolicy(sizePolicy)
        self.thresholdentry.setMinimumSize(QtCore.QSize(60, 0))
        self.thresholdentry.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.thresholdentry.setFont(font)
        self.thresholdentry.setAlignment(QtCore.Qt.AlignCenter)
        self.thresholdentry.setObjectName("thresholdentry")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.thresholdentry)
        self.label_6 = QtWidgets.QLabel(self.groupBox1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_6.sizePolicy().hasHeightForWidth())
        self.label_6.setSizePolicy(sizePolicy)
        self.label_6.setMinimumSize(QtCore.QSize(125, 0))
        self.label_6.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.label_6)
        self.levelthresholdentry = QtWidgets.QLineEdit(self.groupBox1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.levelthresholdentry.sizePolicy().hasHeightForWidth())
        self.levelthresholdentry.setSizePolicy(sizePolicy)
        self.levelthresholdentry.setMinimumSize(QtCore.QSize(60, 0))
        self.levelthresholdentry.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.levelthresholdentry.setFont(font)
        self.levelthresholdentry.setAlignment(QtCore.Qt.AlignCenter)
        self.levelthresholdentry.setObjectName("levelthresholdentry")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.levelthresholdentry)
        self.horizontalLayout_4.addWidget(self.groupBox1)
        self.gridLayout_10.addLayout(self.horizontalLayout_4, 0, 0, 1, 1)
        self.groupBox2 = QtWidgets.QGroupBox(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox2.sizePolicy().hasHeightForWidth())
        self.groupBox2.setSizePolicy(sizePolicy)
        self.groupBox2.setMinimumSize(QtCore.QSize(500, 150))
        self.groupBox2.setMaximumSize(QtCore.QSize(600, 150))
        self.groupBox2.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.groupBox2.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.groupBox2.setObjectName("groupBox2")
        self.gridLayout_11 = QtWidgets.QGridLayout(self.groupBox2)
        self.gridLayout_11.setObjectName("gridLayout_11")
        self.verticalGroupBox_5 = QtWidgets.QGroupBox(self.groupBox2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.verticalGroupBox_5.sizePolicy().hasHeightForWidth())
        self.verticalGroupBox_5.setSizePolicy(sizePolicy)
        self.verticalGroupBox_5.setMinimumSize(QtCore.QSize(225, 75))
        self.verticalGroupBox_5.setMaximumSize(QtCore.QSize(16777215, 50))
        self.verticalGroupBox_5.setAlignment(QtCore.Qt.AlignCenter)
        self.verticalGroupBox_5.setObjectName("verticalGroupBox_5")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.verticalGroupBox_5)
        self.verticalLayout_6.setContentsMargins(5, 0, 5, 5)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setContentsMargins(5, -1, 5, 5)
        self.gridLayout.setHorizontalSpacing(5)
        self.gridLayout.setVerticalSpacing(0)
        self.gridLayout.setObjectName("gridLayout")
        self.previousbutton = QtWidgets.QPushButton(self.verticalGroupBox_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.previousbutton.sizePolicy().hasHeightForWidth())
        self.previousbutton.setSizePolicy(sizePolicy)
        self.previousbutton.setMinimumSize(QtCore.QSize(0, 5))
        self.previousbutton.setMaximumSize(QtCore.QSize(16777215, 40))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.previousbutton.setFont(font)
        self.previousbutton.setObjectName("previousbutton")
        self.gridLayout.addWidget(self.previousbutton, 1, 1, 1, 1)
        self.nextbutton = QtWidgets.QPushButton(self.verticalGroupBox_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.nextbutton.sizePolicy().hasHeightForWidth())
        self.nextbutton.setSizePolicy(sizePolicy)
        self.nextbutton.setMinimumSize(QtCore.QSize(0, 5))
        self.nextbutton.setMaximumSize(QtCore.QSize(16777215, 40))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.nextbutton.setFont(font)
        self.nextbutton.setObjectName("nextbutton")
        self.gridLayout.addWidget(self.nextbutton, 1, 3, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.verticalGroupBox_5)
        self.label_4.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_4.sizePolicy().hasHeightForWidth())
        self.label_4.setSizePolicy(sizePolicy)
        self.label_4.setMinimumSize(QtCore.QSize(200, 0))
        self.label_4.setMaximumSize(QtCore.QSize(16777215, 40))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 0, 1, 1, 2)
        self.gobutton = QtWidgets.QPushButton(self.verticalGroupBox_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.gobutton.sizePolicy().hasHeightForWidth())
        self.gobutton.setSizePolicy(sizePolicy)
        self.gobutton.setMinimumSize(QtCore.QSize(0, 5))
        self.gobutton.setMaximumSize(QtCore.QSize(16777215, 40))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.gobutton.setFont(font)
        self.gobutton.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.gobutton.setObjectName("gobutton")
        self.gridLayout.addWidget(self.gobutton, 1, 2, 1, 1, QtCore.Qt.AlignHCenter)
        self.eventnumberentry = QtWidgets.QLineEdit(self.verticalGroupBox_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.eventnumberentry.sizePolicy().hasHeightForWidth())
        self.eventnumberentry.setSizePolicy(sizePolicy)
        self.eventnumberentry.setMinimumSize(QtCore.QSize(50, 0))
        self.eventnumberentry.setMaximumSize(QtCore.QSize(50, 16777215))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.eventnumberentry.setFont(font)
        self.eventnumberentry.setAlignment(QtCore.Qt.AlignCenter)
        self.eventnumberentry.setObjectName("eventnumberentry")
        self.gridLayout.addWidget(self.eventnumberentry, 0, 3, 1, 1)
        self.verticalLayout_6.addLayout(self.gridLayout)
        self.gridLayout_11.addWidget(self.verticalGroupBox_5, 0, 1, 1, 1, QtCore.Qt.AlignHCenter)
        self.meandtlabel = QtWidgets.QLabel(self.groupBox2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.meandtlabel.sizePolicy().hasHeightForWidth())
        self.meandtlabel.setSizePolicy(sizePolicy)
        self.meandtlabel.setMinimumSize(QtCore.QSize(500, 10))
        self.meandtlabel.setMaximumSize(QtCore.QSize(3000, 10))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.meandtlabel.setFont(font)
        self.meandtlabel.setText("")
        self.meandtlabel.setObjectName("meandtlabel")
        self.gridLayout_11.addWidget(self.meandtlabel, 3, 0, 1, 2)
        self.eventcounterlabel = QtWidgets.QLabel(self.groupBox2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.eventcounterlabel.sizePolicy().hasHeightForWidth())
        self.eventcounterlabel.setSizePolicy(sizePolicy)
        self.eventcounterlabel.setMinimumSize(QtCore.QSize(500, 10))
        self.eventcounterlabel.setMaximumSize(QtCore.QSize(3000, 10))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.eventcounterlabel.setFont(font)
        self.eventcounterlabel.setText("")
        self.eventcounterlabel.setObjectName("eventcounterlabel")
        self.gridLayout_11.addWidget(self.eventcounterlabel, 5, 0, 1, 2)
        self.filelabel = QtWidgets.QLabel(self.groupBox2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.filelabel.sizePolicy().hasHeightForWidth())
        self.filelabel.setSizePolicy(sizePolicy)
        self.filelabel.setMinimumSize(QtCore.QSize(500, 10))
        self.filelabel.setMaximumSize(QtCore.QSize(3000, 10))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.filelabel.setFont(font)
        self.filelabel.setText("")
        self.filelabel.setObjectName("filelabel")
        self.gridLayout_11.addWidget(self.filelabel, 6, 0, 1, 2)
        self.meandwelllabel = QtWidgets.QLabel(self.groupBox2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.meandwelllabel.sizePolicy().hasHeightForWidth())
        self.meandwelllabel.setSizePolicy(sizePolicy)
        self.meandwelllabel.setMinimumSize(QtCore.QSize(500, 10))
        self.meandwelllabel.setMaximumSize(QtCore.QSize(3000, 10))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.meandwelllabel.setFont(font)
        self.meandwelllabel.setText("")
        self.meandwelllabel.setObjectName("meandwelllabel")
        self.gridLayout_11.addWidget(self.meandwelllabel, 1, 0, 1, 2)
        self.meandelilabel = QtWidgets.QLabel(self.groupBox2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.meandelilabel.sizePolicy().hasHeightForWidth())
        self.meandelilabel.setSizePolicy(sizePolicy)
        self.meandelilabel.setMinimumSize(QtCore.QSize(500, 10))
        self.meandelilabel.setMaximumSize(QtCore.QSize(3000, 10))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.meandelilabel.setFont(font)
        self.meandelilabel.setText("")
        self.meandelilabel.setObjectName("meandelilabel")
        self.gridLayout_11.addWidget(self.meandelilabel, 2, 0, 1, 1)
        self.gridLayout_10.addWidget(self.groupBox2, 0, 1, 1, 1)
        self.verticalGroupBox_6 = QtWidgets.QGroupBox(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.verticalGroupBox_6.sizePolicy().hasHeightForWidth())
        self.verticalGroupBox_6.setSizePolicy(sizePolicy)
        self.verticalGroupBox_6.setMinimumSize(QtCore.QSize(125, 150))
        self.verticalGroupBox_6.setMaximumSize(QtCore.QSize(125, 150))
        self.verticalGroupBox_6.setObjectName("verticalGroupBox_6")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.verticalGroupBox_6)
        self.gridLayout_5.setContentsMargins(0, 0, 0, 5)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.deleteeventbutton = QtWidgets.QPushButton(self.verticalGroupBox_6)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.deleteeventbutton.sizePolicy().hasHeightForWidth())
        self.deleteeventbutton.setSizePolicy(sizePolicy)
        self.deleteeventbutton.setMinimumSize(QtCore.QSize(100, 20))
        self.deleteeventbutton.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.deleteeventbutton.setFont(font)
        self.deleteeventbutton.setObjectName("deleteeventbutton")
        self.gridLayout_5.addWidget(self.deleteeventbutton, 0, 0, 1, 1)
        self.concatenatebutton = QtWidgets.QPushButton(self.verticalGroupBox_6)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.concatenatebutton.sizePolicy().hasHeightForWidth())
        self.concatenatebutton.setSizePolicy(sizePolicy)
        self.concatenatebutton.setMinimumSize(QtCore.QSize(100, 20))
        self.concatenatebutton.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.concatenatebutton.setFont(font)
        self.concatenatebutton.setObjectName("concatenatebutton")
        self.gridLayout_5.addWidget(self.concatenatebutton, 1, 0, 1, 1)
        self.showcatbutton = QtWidgets.QPushButton(self.verticalGroupBox_6)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.showcatbutton.sizePolicy().hasHeightForWidth())
        self.showcatbutton.setSizePolicy(sizePolicy)
        self.showcatbutton.setMinimumSize(QtCore.QSize(100, 20))
        self.showcatbutton.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.showcatbutton.setFont(font)
        self.showcatbutton.setObjectName("showcatbutton")
        self.gridLayout_5.addWidget(self.showcatbutton, 2, 0, 1, 1)
        self.savecatbutton = QtWidgets.QPushButton(self.verticalGroupBox_6)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.savecatbutton.sizePolicy().hasHeightForWidth())
        self.savecatbutton.setSizePolicy(sizePolicy)
        self.savecatbutton.setMinimumSize(QtCore.QSize(100, 20))
        self.savecatbutton.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.savecatbutton.setFont(font)
        self.savecatbutton.setObjectName("savecatbutton")
        self.gridLayout_5.addWidget(self.savecatbutton, 3, 0, 1, 1)
        self.savefitsbutton = QtWidgets.QPushButton(self.verticalGroupBox_6)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.savefitsbutton.sizePolicy().hasHeightForWidth())
        self.savefitsbutton.setSizePolicy(sizePolicy)
        self.savefitsbutton.setMinimumSize(QtCore.QSize(100, 20))
        self.savefitsbutton.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.savefitsbutton.setFont(font)
        self.savefitsbutton.setObjectName("savefitsbutton")
        self.gridLayout_5.addWidget(self.savefitsbutton, 4, 0, 1, 1)
        self.savetargetbutton = QtWidgets.QPushButton(self.verticalGroupBox_6)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.savetargetbutton.sizePolicy().hasHeightForWidth())
        self.savetargetbutton.setSizePolicy(sizePolicy)
        self.savetargetbutton.setMinimumSize(QtCore.QSize(100, 20))
        self.savetargetbutton.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.savetargetbutton.setFont(font)
        self.savetargetbutton.setObjectName("savetargetbutton")
        self.gridLayout_5.addWidget(self.savetargetbutton, 5, 0, 1, 1)
        self.gridLayout_10.addWidget(self.verticalGroupBox_6, 0, 2, 1, 1)
        self.groupBox3 = QtWidgets.QGroupBox(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox3.sizePolicy().hasHeightForWidth())
        self.groupBox3.setSizePolicy(sizePolicy)
        self.groupBox3.setObjectName("groupBox3")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.groupBox3)
        self.gridLayout_4.setSizeConstraint(QtWidgets.QLayout.SetMaximumSize)
        self.gridLayout_4.setContentsMargins(10, 10, 10, 5)
        self.gridLayout_4.setVerticalSpacing(5)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.signalplot = GraphicsLayoutWidget(self.groupBox3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.signalplot.sizePolicy().hasHeightForWidth())
        self.signalplot.setSizePolicy(sizePolicy)
        self.signalplot.setMinimumSize(QtCore.QSize(0, 225))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.signalplot.setFont(font)
        self.signalplot.setStyleSheet("border-color: rgb(0, 0, 0);")
        self.signalplot.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.signalplot.setObjectName("signalplot")
        self.gridLayout_4.addWidget(self.signalplot, 0, 0, 1, 1)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setContentsMargins(0, -1, 0, -1)
        self.horizontalLayout_3.setSpacing(5)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.eventplot = GraphicsLayoutWidget(self.groupBox3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.eventplot.sizePolicy().hasHeightForWidth())
        self.eventplot.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Kozuka Gothic Pro L")
        font.setPointSize(20)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(3)
        self.eventplot.setFont(font)
        self.eventplot.setStyleSheet("font: 25 20pt \"Kozuka Gothic Pro L\";\n"
"border-color: rgb(0, 0, 0);")
        self.eventplot.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.eventplot.setObjectName("eventplot")
        self.horizontalLayout_3.addWidget(self.eventplot)
        self.tabWidget = QtWidgets.QTabWidget(self.groupBox3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tabWidget.sizePolicy().hasHeightForWidth())
        self.tabWidget.setSizePolicy(sizePolicy)
        self.tabWidget.setMaximumSize(QtCore.QSize(16777215, 16777206))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        self.tabWidget.setFont(font)
        self.tabWidget.setTabPosition(QtWidgets.QTabWidget.East)
        self.tabWidget.setTabShape(QtWidgets.QTabWidget.Rounded)
        self.tabWidget.setElideMode(QtCore.Qt.ElideMiddle)
        self.tabWidget.setDocumentMode(False)
        self.tabWidget.setObjectName("tabWidget")
        self.scattertab = QtWidgets.QWidget()
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        self.scattertab.setFont(font)
        self.scattertab.setObjectName("scattertab")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.scattertab)
        self.gridLayout_3.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_3.setSpacing(0)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.scatterplot = GraphicsLayoutWidget(self.scattertab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.scatterplot.sizePolicy().hasHeightForWidth())
        self.scatterplot.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Kozuka Gothic Pro L")
        font.setPointSize(20)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(3)
        self.scatterplot.setFont(font)
        self.scatterplot.setStyleSheet("font: 25 20pt \"Kozuka Gothic Pro L\";")
        self.scatterplot.setObjectName("scatterplot")
        self.gridLayout_3.addWidget(self.scatterplot, 0, 0, 1, 1)
        self.tabWidget.addTab(self.scattertab, "")
        self.frachisttab = QtWidgets.QWidget()
        self.frachisttab.setObjectName("frachisttab")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.frachisttab)
        self.gridLayout_6.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_6.setSpacing(0)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.frachistplot = GraphicsLayoutWidget(self.frachisttab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frachistplot.sizePolicy().hasHeightForWidth())
        self.frachistplot.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Kozuka Gothic Pro L")
        font.setPointSize(20)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(3)
        self.frachistplot.setFont(font)
        self.frachistplot.setStyleSheet("font: 25 20pt \"Kozuka Gothic Pro L\";")
        self.frachistplot.setObjectName("frachistplot")
        self.gridLayout_6.addWidget(self.frachistplot, 0, 0, 1, 1)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_7 = QtWidgets.QLabel(self.frachisttab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_7.sizePolicy().hasHeightForWidth())
        self.label_7.setSizePolicy(sizePolicy)
        self.label_7.setObjectName("label_7")
        self.horizontalLayout_2.addWidget(self.label_7)
        self.fracbins = QtWidgets.QLineEdit(self.frachisttab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.fracbins.sizePolicy().hasHeightForWidth())
        self.fracbins.setSizePolicy(sizePolicy)
        self.fracbins.setAlignment(QtCore.Qt.AlignCenter)
        self.fracbins.setObjectName("fracbins")
        self.horizontalLayout_2.addWidget(self.fracbins)
        self.gridLayout_6.addLayout(self.horizontalLayout_2, 1, 0, 1, 1)
        self.tabWidget.addTab(self.frachisttab, "")
        self.delitab = QtWidgets.QWidget()
        self.delitab.setObjectName("delitab")
        self.gridLayout_7 = QtWidgets.QGridLayout(self.delitab)
        self.gridLayout_7.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_7.setSpacing(0)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.delihistplot = GraphicsLayoutWidget(self.delitab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.delihistplot.sizePolicy().hasHeightForWidth())
        self.delihistplot.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Kozuka Gothic Pro L")
        font.setPointSize(20)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(3)
        self.delihistplot.setFont(font)
        self.delihistplot.setStyleSheet("font: 25 20pt \"Kozuka Gothic Pro L\";")
        self.delihistplot.setObjectName("delihistplot")
        self.gridLayout_7.addWidget(self.delihistplot, 0, 0, 1, 1)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.label_9 = QtWidgets.QLabel(self.delitab)
        self.label_9.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_9.sizePolicy().hasHeightForWidth())
        self.label_9.setSizePolicy(sizePolicy)
        self.label_9.setObjectName("label_9")
        self.horizontalLayout_7.addWidget(self.label_9)
        self.delibins = QtWidgets.QLineEdit(self.delitab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.delibins.sizePolicy().hasHeightForWidth())
        self.delibins.setSizePolicy(sizePolicy)
        self.delibins.setAlignment(QtCore.Qt.AlignCenter)
        self.delibins.setObjectName("delibins")
        self.horizontalLayout_7.addWidget(self.delibins)
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.label_10 = QtWidgets.QLabel(self.delitab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_10.sizePolicy().hasHeightForWidth())
        self.label_10.setSizePolicy(sizePolicy)
        self.label_10.setObjectName("label_10")
        self.horizontalLayout_9.addWidget(self.label_10)
        self.delirange0 = QtWidgets.QLineEdit(self.delitab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.delirange0.sizePolicy().hasHeightForWidth())
        self.delirange0.setSizePolicy(sizePolicy)
        self.delirange0.setAlignment(QtCore.Qt.AlignCenter)
        self.delirange0.setObjectName("delirange0")
        self.horizontalLayout_9.addWidget(self.delirange0)
        self.label_12 = QtWidgets.QLabel(self.delitab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_12.sizePolicy().hasHeightForWidth())
        self.label_12.setSizePolicy(sizePolicy)
        self.label_12.setObjectName("label_12")
        self.horizontalLayout_9.addWidget(self.label_12)
        self.delirange1 = QtWidgets.QLineEdit(self.delitab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.delirange1.sizePolicy().hasHeightForWidth())
        self.delirange1.setSizePolicy(sizePolicy)
        self.delirange1.setAlignment(QtCore.Qt.AlignCenter)
        self.delirange1.setObjectName("delirange1")
        self.horizontalLayout_9.addWidget(self.delirange1)
        self.label_11 = QtWidgets.QLabel(self.delitab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_11.sizePolicy().hasHeightForWidth())
        self.label_11.setSizePolicy(sizePolicy)
        self.label_11.setObjectName("label_11")
        self.horizontalLayout_9.addWidget(self.label_11)
        self.horizontalLayout_7.addLayout(self.horizontalLayout_9)
        self.gridLayout_7.addLayout(self.horizontalLayout_7, 1, 0, 1, 1)
        self.tabWidget.addTab(self.delitab, "")
        self.dwelltab = QtWidgets.QWidget()
        self.dwelltab.setObjectName("dwelltab")
        self.gridLayout_8 = QtWidgets.QGridLayout(self.dwelltab)
        self.gridLayout_8.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_8.setSpacing(0)
        self.gridLayout_8.setObjectName("gridLayout_8")
        self.dwellhistplot = GraphicsLayoutWidget(self.dwelltab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.dwellhistplot.sizePolicy().hasHeightForWidth())
        self.dwellhistplot.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Kozuka Gothic Pro L")
        font.setPointSize(20)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(3)
        self.dwellhistplot.setFont(font)
        self.dwellhistplot.setStyleSheet("font: 25 20pt \"Kozuka Gothic Pro L\";")
        self.dwellhistplot.setObjectName("dwellhistplot")
        self.gridLayout_8.addWidget(self.dwellhistplot, 0, 0, 1, 1)
        self.horizontalLayout_14 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_14.setObjectName("horizontalLayout_14")
        self.label_21 = QtWidgets.QLabel(self.dwelltab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_21.sizePolicy().hasHeightForWidth())
        self.label_21.setSizePolicy(sizePolicy)
        self.label_21.setObjectName("label_21")
        self.horizontalLayout_14.addWidget(self.label_21)
        self.dwellbins = QtWidgets.QLineEdit(self.dwelltab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.dwellbins.sizePolicy().hasHeightForWidth())
        self.dwellbins.setSizePolicy(sizePolicy)
        self.dwellbins.setAlignment(QtCore.Qt.AlignCenter)
        self.dwellbins.setObjectName("dwellbins")
        self.horizontalLayout_14.addWidget(self.dwellbins)
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.label_22 = QtWidgets.QLabel(self.dwelltab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_22.sizePolicy().hasHeightForWidth())
        self.label_22.setSizePolicy(sizePolicy)
        self.label_22.setObjectName("label_22")
        self.horizontalLayout_10.addWidget(self.label_22)
        self.dwellrange0 = QtWidgets.QLineEdit(self.dwelltab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.dwellrange0.sizePolicy().hasHeightForWidth())
        self.dwellrange0.setSizePolicy(sizePolicy)
        self.dwellrange0.setAlignment(QtCore.Qt.AlignCenter)
        self.dwellrange0.setObjectName("dwellrange0")
        self.horizontalLayout_10.addWidget(self.dwellrange0)
        self.label_23 = QtWidgets.QLabel(self.dwelltab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_23.sizePolicy().hasHeightForWidth())
        self.label_23.setSizePolicy(sizePolicy)
        self.label_23.setObjectName("label_23")
        self.horizontalLayout_10.addWidget(self.label_23)
        self.dwellrange1 = QtWidgets.QLineEdit(self.dwelltab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.dwellrange1.sizePolicy().hasHeightForWidth())
        self.dwellrange1.setSizePolicy(sizePolicy)
        self.dwellrange1.setAlignment(QtCore.Qt.AlignCenter)
        self.dwellrange1.setObjectName("dwellrange1")
        self.horizontalLayout_10.addWidget(self.dwellrange1)
        self.label_24 = QtWidgets.QLabel(self.dwelltab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_24.sizePolicy().hasHeightForWidth())
        self.label_24.setSizePolicy(sizePolicy)
        self.label_24.setObjectName("label_24")
        self.horizontalLayout_10.addWidget(self.label_24)
        self.horizontalLayout_14.addLayout(self.horizontalLayout_10)
        self.gridLayout_8.addLayout(self.horizontalLayout_14, 1, 0, 1, 1)
        self.tabWidget.addTab(self.dwelltab, "")
        self.dttab = QtWidgets.QWidget()
        self.dttab.setObjectName("dttab")
        self.gridLayout_9 = QtWidgets.QGridLayout(self.dttab)
        self.gridLayout_9.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_9.setSpacing(0)
        self.gridLayout_9.setObjectName("gridLayout_9")
        self.dthistplot = GraphicsLayoutWidget(self.dttab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.dthistplot.sizePolicy().hasHeightForWidth())
        self.dthistplot.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Kozuka Gothic Pro L")
        font.setPointSize(20)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(3)
        self.dthistplot.setFont(font)
        self.dthistplot.setStyleSheet("font: 25 20pt \"Kozuka Gothic Pro L\";")
        self.dthistplot.setObjectName("dthistplot")
        self.gridLayout_9.addWidget(self.dthistplot, 0, 0, 1, 1)
        self.horizontalLayout_18 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_18.setObjectName("horizontalLayout_18")
        self.label_25 = QtWidgets.QLabel(self.dttab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_25.sizePolicy().hasHeightForWidth())
        self.label_25.setSizePolicy(sizePolicy)
        self.label_25.setObjectName("label_25")
        self.horizontalLayout_18.addWidget(self.label_25)
        self.dtbins = QtWidgets.QLineEdit(self.dttab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.dtbins.sizePolicy().hasHeightForWidth())
        self.dtbins.setSizePolicy(sizePolicy)
        self.dtbins.setAlignment(QtCore.Qt.AlignCenter)
        self.dtbins.setObjectName("dtbins")
        self.horizontalLayout_18.addWidget(self.dtbins)
        self.horizontalLayout_19 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_19.setObjectName("horizontalLayout_19")
        self.label_26 = QtWidgets.QLabel(self.dttab)
        self.label_26.setObjectName("label_26")
        self.horizontalLayout_19.addWidget(self.label_26)
        self.dtrange0 = QtWidgets.QLineEdit(self.dttab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.dtrange0.sizePolicy().hasHeightForWidth())
        self.dtrange0.setSizePolicy(sizePolicy)
        self.dtrange0.setAlignment(QtCore.Qt.AlignCenter)
        self.dtrange0.setObjectName("dtrange0")
        self.horizontalLayout_19.addWidget(self.dtrange0)
        self.label_27 = QtWidgets.QLabel(self.dttab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_27.sizePolicy().hasHeightForWidth())
        self.label_27.setSizePolicy(sizePolicy)
        self.label_27.setObjectName("label_27")
        self.horizontalLayout_19.addWidget(self.label_27)
        self.dtrange1 = QtWidgets.QLineEdit(self.dttab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.dtrange1.sizePolicy().hasHeightForWidth())
        self.dtrange1.setSizePolicy(sizePolicy)
        self.dtrange1.setAlignment(QtCore.Qt.AlignCenter)
        self.dtrange1.setObjectName("dtrange1")
        self.horizontalLayout_19.addWidget(self.dtrange1)
        self.label_28 = QtWidgets.QLabel(self.dttab)
        self.label_28.setObjectName("label_28")
        self.horizontalLayout_19.addWidget(self.label_28)
        self.horizontalLayout_18.addLayout(self.horizontalLayout_19)
        self.gridLayout_9.addLayout(self.horizontalLayout_18, 1, 0, 1, 1)
        self.tabWidget.addTab(self.dttab, "")
        self.horizontalLayout_3.addWidget(self.tabWidget)
        self.gridLayout_4.addLayout(self.horizontalLayout_3, 1, 0, 1, 1)
        self.eventinfolabel = QtWidgets.QLabel(self.groupBox3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.eventinfolabel.sizePolicy().hasHeightForWidth())
        self.eventinfolabel.setSizePolicy(sizePolicy)
        self.eventinfolabel.setMinimumSize(QtCore.QSize(500, 25))
        self.eventinfolabel.setMaximumSize(QtCore.QSize(3000, 25))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.eventinfolabel.setFont(font)
        self.eventinfolabel.setText("")
        self.eventinfolabel.setObjectName("eventinfolabel")
        self.gridLayout_4.addWidget(self.eventinfolabel, 2, 0, 1, 1)
        self.gridLayout_10.addWidget(self.groupBox3, 1, 0, 1, 3)
        PythIon.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(PythIon)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1254, 22))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuEdit = QtWidgets.QMenu(self.menubar)
        self.menuEdit.setObjectName("menuEdit")
        PythIon.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(PythIon)
        self.statusbar.setObjectName("statusbar")
        PythIon.setStatusBar(self.statusbar)
        self.actionInvert = QtWidgets.QAction(PythIon)
        self.actionInvert.setObjectName("actionInvert")
        self.actionsetbuffer = QtWidgets.QAction(PythIon)
        self.actionsetbuffer.setObjectName("actionsetbuffer")
        self.Poresizeraction = QtWidgets.QAction(PythIon)
        self.Poresizeraction.setObjectName("Poresizeraction")
        self.actionBatch_Process = QtWidgets.QAction(PythIon)
        self.actionBatch_Process.setObjectName("actionBatch_Process")
        self.menuFile.addAction(self.Poresizeraction)
        self.menuFile.addAction(self.actionBatch_Process)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuEdit.menuAction())

        self.retranslateUi(PythIon)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(PythIon)

    def retranslateUi(self, PythIon):
        _translate = QtCore.QCoreApplication.translate
        PythIon.setWindowTitle(_translate("PythIon", "PythIon"))
        self.loadbutton.setText(_translate("PythIon", "LOAD"))
        self.cutbutton.setText(_translate("PythIon", "CUT"))
        self.nextfilebutton.setText(_translate("PythIon", "NEXT"))
        self.baselinebutton.setText(_translate("PythIon", "BASELINE"))
        self.previousfilebutton.setText(_translate("PythIon", "PREVIOUS"))
        self.analyzebutton.setText(_translate("PythIon", "ANALYZE"))
        self.invertbutton.setText(_translate("PythIon", "INVERT"))
        self.fitbutton.setText(_translate("PythIon", "FIT"))
        self.clearscatterbutton.setText(_translate("PythIon", "CLEAR DATA"))
        self.loaddatabutton.setText(_translate("PythIon", "LOAD DATA"))
        self.label.setText(_translate("PythIon", "Low Pass Filter (kHz)"))
        self.LPentry.setText(_translate("PythIon", "100"))
        self.label_2.setText(_translate("PythIon", "Output Samplerate (kHz)"))
        self.outputsamplerateentry.setText(_translate("PythIon", "4166.67"))
        self.label_5.setText(_translate("PythIon", "Event Buffer (samples)"))
        self.eventbufferentry.setText(_translate("PythIon", "1000"))
        self.label_3.setText(_translate("PythIon", "Threshold (nA)"))
        self.thresholdentry.setText(_translate("PythIon", ".3"))
        self.label_6.setText(_translate("PythIon", "Level Threshold (nA)"))
        self.levelthresholdentry.setText(_translate("PythIon", "None"))
        self.previousbutton.setText(_translate("PythIon", "Previous"))
        self.nextbutton.setText(_translate("PythIon", "Next"))
        self.label_4.setText(_translate("PythIon", "Enter Event Number To View"))
        self.gobutton.setText(_translate("PythIon", "Go"))
        self.eventnumberentry.setText(_translate("PythIon", "0"))
        self.deleteeventbutton.setText(_translate("PythIon", "DELETE EVENT"))
        self.concatenatebutton.setText(_translate("PythIon", "CONCATENATE"))
        self.showcatbutton.setText(_translate("PythIon", "SHOW CAT. TRACE"))
        self.savecatbutton.setText(_translate("PythIon", "SAVE CAT. TRACE"))
        self.savefitsbutton.setText(_translate("PythIon", "SAVE EVENT FITS"))
        self.savetargetbutton.setText(_translate("PythIon", "SAVE TARGET"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.scattertab), _translate("PythIon", "Scatter"))
        self.label_7.setText(_translate("PythIon", "Bins:"))
        self.fracbins.setText(_translate("PythIon", "50"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.frachisttab), _translate("PythIon", "Frac"))
        self.label_9.setText(_translate("PythIon", "Bins"))
        self.delibins.setText(_translate("PythIon", "50"))
        self.label_10.setText(_translate("PythIon", "("))
        self.delirange0.setText(_translate("PythIon", "0"))
        self.label_12.setText(_translate("PythIon", "-"))
        self.delirange1.setText(_translate("PythIon", "1"))
        self.label_11.setText(_translate("PythIon", ")"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.delitab), _translate("PythIon", "Deli"))
        self.label_21.setText(_translate("PythIon", "Bins"))
        self.dwellbins.setText(_translate("PythIon", "100"))
        self.label_22.setText(_translate("PythIon", "("))
        self.dwellrange0.setText(_translate("PythIon", "0"))
        self.label_23.setText(_translate("PythIon", "-"))
        self.dwellrange1.setText(_translate("PythIon", "5"))
        self.label_24.setText(_translate("PythIon", ")"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.dwelltab), _translate("PythIon", "Dwell"))
        self.label_25.setText(_translate("PythIon", "Bins"))
        self.dtbins.setText(_translate("PythIon", "100"))
        self.label_26.setText(_translate("PythIon", "("))
        self.dtrange0.setText(_translate("PythIon", "0"))
        self.label_27.setText(_translate("PythIon", "-"))
        self.dtrange1.setText(_translate("PythIon", "1"))
        self.label_28.setText(_translate("PythIon", ")"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.dttab), _translate("PythIon", "dt"))
        self.menuFile.setTitle(_translate("PythIon", "File"))
        self.menuEdit.setTitle(_translate("PythIon", "Edit"))
        self.actionInvert.setText(_translate("PythIon", "Invert data"))
        self.actionsetbuffer.setText(_translate("PythIon", "Set Event Buffer Size"))
        self.Poresizeraction.setText(_translate("PythIon", "PoreSizer"))
        self.actionBatch_Process.setText(_translate("PythIon", "Batch Process"))

from pyqtgraph import GraphicsLayoutWidget
